### 1. Testing method

NB: Already went through paraphrasing prior to this testing the method but assume you don't want any more IPYNBs than necessary so left that one out. First section of this file tests the method works as expected. Second half actually runs the translation of the 2000 row dataset.

______________

In [47]:
from openai import OpenAI
from bert_score import score
import pandas as pd
import numpy as np
import getpass
import time
import os

In [48]:
# use getpass to pass api key over so as not to inclue here
API_KEY = getpass.getpass("Enter OpenAI API key: ")

# create client
client = OpenAI(api_key = API_KEY)

print("Open AI client created.")

Enter OpenAI API key:  ········

Open AI client created.

In [19]:
# set up csv, take copy of first 20 rows for initial testing

csv_file = "final_human_dataset_copy.csv"
df = pd.read_csv(csv_file)
test = df.head(20).copy()
print("Test text: ", len(test))

Test text:  20

Now need to set up the prompts that will be passed to Open AI for paraphrasing. Seperate prompts for light paraphrase, heavy paraphrase, translation to French and translation from French back to English.

In [49]:
light_para_prompt = """

Paraphrase the following text lightly.

Make limited changes to the original wording, phrasing and sentence structure.
Replace some words and phrases with alternatives.
Make minor grammatical changes.

Preserve the original meaning, factual information, level of detail, structure and ideas as closely as possible. 
The result should be a paraphrase that remains very close to the original text.
Do not add new information, remove information, or summarise the text.
Keep the length similar to the original.

Return only the paraphrased text.


TEXT: {text}

"""

In [50]:
heavy_para_prompt = """

Paraphrase the following text heavily.

Make substantial changes to the original wording, phrasing and sentence structure.
Make major grammatical changes, and use substantially different vocabulary.
Reorganise sentences and vary how ideas are expressed where appropriate.


Preserve the original meaning, factual information, level of detail, and ideas as closely as possible.
The result should be a paraphrase that is substantially different in wording, structure and order to 
the original text whilst preserving its meaning.
Do not add new information, remove information, or summarise the text.
Keep the length similar to the original.

Return only the paraphrased text.


TEXT: {text}

"""

In [51]:
trans_french_prompt = """

Translate the following English text into French.

Create a natural and fluent translation.
Preserve the original meaning, factual information, level of detail, and ideas as closely as possible.
Preserve any names, dates, numbers and technical information.

Do not add new information, remove information, or summarise the text.
Keep the length similar to the original.

Return only the translated French text.


TEXT: {text}

"""

In [52]:
trans_english_prompt = """

Translate the following French text into English.

Create a natural and fluent translation.
Preserve the original meaning, factual information, level of detail, and ideas as closely as possible.
Preserve any names, dates, numbers and technical information.

Do not add new information, remove information, or summarise the text.
Keep the length similar to the original.

Return only the translated English text.


TEXT: {text}

"""

Do a test on one sample...

In [53]:
# function to send prompt 
def send_prompt(prompt, model):

    # send request to open AI
    response = client.responses.create(
        # specify model
        model = model,
        # send prompt
        input = prompt
    )

    # get response, trim whitespace
    return response.output_text.strip()

In [24]:
# get text from first row of test data
text = test.iloc[5]["text"]

# send light paraphrasing prmopt to llm
light = send_prompt(
    light_para_prompt.format(text = text),
    # specify luna (cheaper / lesser) model
    "gpt-5.6-luna"
)

# same but for heavy
heavy = send_prompt(
    heavy_para_prompt.format(text = text),
    "gpt-5.6-luna"
)

# run translation to french
french = send_prompt(
    trans_french_prompt.format(text = text),
    "gpt-5.6-luna"
)

# translate that french back to english
english = send_prompt(
    # input is now the french translation
    trans_english_prompt.format(text = french),
    "gpt-5.6-luna"
)

print("Original\n")
print(text)

print("\n\nLight\n")
print(light)

print("\n\nHeavy\n")
print(heavy)

print("\n\nFrench\n")
print(french)

print("\n\nTranslated back to English\n")
print(english)

Original

Severe Tropical Cyclone Xavier was a strong pre-season cyclone that formed on October 20, 2006, to the north of the Santa Cruz Islands. Cyclone Xavier was also the strongest storm of the season. During the next day it rapidly developed and was designated as Tropical Depression 01F later that day, before being designated as Tropical Cyclone Xavier while over Santa Cruz early on October 22. Later on October 22, Xavier intensified into a category 3 severe tropical cyclone on the Australian Tropical Cyclone Intensity Scale, before passing over Tikopia early the next day. Xavier then reached its peak wind speeds of 175 km/h (110 mph 10-min), which made it a Category 4 cyclone early on October 24. Xavier stayed at its peak wind speeds until early the next day when it started to rapidly weaken, becoming a depression early on October 26. The remnants of Xavier persisted until October 28 before dissipating. There were no casualties reported as a result of the storm and little impact reported in the Solomon Islands and Vanuatu. During October 20, 2006 the Fiji Meteorological Service and the United States Joint Typhoon Warning Center started to monitor a tropical depression, that had developed within the South Pacific Convergence Zone to the north of Temotu Province in the Solomon Islands. The system was located within an area of low to moderate vertical wind shear and had a good outflow in its northern and eastern quadrants. Over the next day conditions surrounding the system rapidly became favourable for further development, with convection starting to wrap into a well defined low level circulation centre. As a result, the depression rapidly developed further and was named Xavier by the FMS during October 22, after it had become a category 1 tropical cyclone on the Australian tropical cyclone intensity scale. After the system was named the JTWC initiated advisories on the system and designated it as Tropical Cyclone 01P, while it was located over the Santa Cruz Islands. Throughout October 22, Xavier's rapid intensification continued with it developing an eye feature and becoming a category 3 severe tropical cyclone. During that day the system performed a small cyclonic loop over Temotu Province and passed near or over the Santa Cruz Island of Tikopia. The systems rapid intensification subsequently slowed down during October 23, as an upper-level anticyclone located to the northwest of the system impeded the systems outflow. The system also started to move south-eastwards during that day, as a trough of low pressure created a break in the ridge of high pressure that was steering Xavier.


Light

Severe Tropical Cyclone Xavier was a powerful pre-season cyclone that formed on October 20, 2006, north of the Santa Cruz Islands. Cyclone Xavier was also the strongest storm of the season. Over the following day, it rapidly strengthened and was designated Tropical Depression 01F later that day, before being named Tropical Cyclone Xavier while over Santa Cruz early on October 22. Later on October 22, Xavier intensified into a category 3 severe tropical cyclone on the Australian Tropical Cyclone Intensity Scale, before passing over Tikopia early the next day. Xavier then reached peak wind speeds of 175 km/h (110 mph 10-min), making it a Category 4 cyclone early on October 24. Xavier maintained its peak wind speeds until early the following day, when it began to weaken rapidly, becoming a depression early on October 26. The remnants of Xavier remained until October 28 before dissipating. No casualties were reported as a result of the storm, and little impact was reported in the Solomon Islands and Vanuatu.

On October 20, 2006, the Fiji Meteorological Service and the United States Joint Typhoon Warning Center began monitoring a tropical depression that had developed within the South Pacific Convergence Zone north of Temotu Province in the Solomon Islands. The system was situated in an area of low to moderate vertical wind shear and had good outflow in its northern and eastern quadrants. Over the next day, conditions around the system quickly became favourable for further development, with convection beginning to wrap around a well-defined low-level circulation centre. As a result, the depression strengthened rapidly and was named Xavier by the FMS during October 22, after becoming a category 1 tropical cyclone on the Australian tropical cyclone intensity scale. After the system was named, the JTWC initiated advisories for it and designated it Tropical Cyclone 01P, while it was located over the Santa Cruz Islands. Throughout October 22, Xavier’s rapid intensification continued, as it developed an eye feature and became a category 3 severe tropical cyclone. During that day, the system made a small cyclonic loop over Temotu Province and passed near or over the Santa Cruz Island of Tikopia. The system’s rapid intensification then slowed during October 23, as an upper-level anticyclone northwest of the system hindered its outflow. The system also began moving southeastward that day, as a low-pressure trough created a break in the high-pressure ridge steering Xavier.


Heavy

Severe Tropical Cyclone Xavier was an intense early-season system that originated north of the Santa Cruz Islands on October 20, 2006. It ultimately became the season’s most powerful cyclone. Rapid strengthening occurred over the following 24 hours, and the Fiji Meteorological Service (FMS) classified it as Tropical Depression 01F later on October 21. By the early hours of October 22, while situated over the Santa Cruz Islands, it had strengthened sufficiently to be named Tropical Cyclone Xavier.

Xavier continued to intensify and was upgraded to a Category 3 severe tropical cyclone on the Australian Tropical Cyclone Intensity Scale later on October 22. It moved across or near Tikopia early the following day. Early on October 24, the cyclone attained maximum sustained winds of 175 km/h (110 mph, 10-minute average), making it a Category 4 system. Those peak winds persisted until early October 25, after which Xavier weakened rapidly and was downgraded to a depression during the early hours of October 26. Its remaining circulation lasted until October 28, when it finally dissipated. No deaths were attributed to the cyclone, and only limited effects were reported in the Solomon Islands and Vanuatu.

On October 20, 2006, the FMS and the United States Joint Typhoon Warning Center (JTWC) began tracking a tropical depression that had formed within the South Pacific Convergence Zone, north of the Solomon Islands’ Temotu Province. At that stage, the disturbance lay in an environment of low to moderate vertical wind shear and possessed favourable outflow to its north and east. Conditions improved markedly during the next day. Convection began consolidating around a clearly defined low-level circulation centre, allowing the depression to strengthen quickly.

After the system reached Category 1 intensity under the Australian scale, the FMS gave it the name Xavier on October 22. The JTWC then commenced issuing advisories and identified the system as Tropical Cyclone 01P while it was positioned over the Santa Cruz Islands. Rapid intensification continued throughout October 22, as an eye-like feature developed and Xavier advanced to severe tropical cyclone status at Category 3. During the same period, the cyclone completed a small clockwise loop over Temotu Province and passed close to, or directly across, Tikopia in the Santa Cruz Islands.

Xavier’s strengthening rate decreased afterward on October 23. An upper-level anticyclone to the system’s northwest restricted its ability to vent air outward. On that day, Xavier also began heading southeast, after a low-pressure trough opened a gap in the high-pressure ridge that had previously been directing its movement.


French

Le cyclone tropical sévère Xavier était un puissant cyclone d’avant-saison qui s’est formé le 20 octobre 2006 au nord des îles Santa Cruz. Le cyclone Xavier a également été la tempête la plus intense de la saison. Au cours de la journée suivante, il s’est rapidement développé et a été classé comme dépression tropicale 01F plus tard dans la journée, avant d’être désigné comme cyclone tropical Xavier alors qu’il se trouvait au-dessus des îles Santa Cruz au début du 22 octobre. Plus tard le 22 octobre, Xavier s’est intensifié en cyclone tropical sévère de catégorie 3 sur l’échelle australienne d’intensité des cyclones tropicaux, avant de passer au-dessus de Tikopia au début du jour suivant. Xavier a ensuite atteint sa vitesse maximale de 175 km/h (110 mi/h sur 10 min), ce qui en a fait un cyclone de catégorie 4 au début du 24 octobre. Xavier a conservé sa vitesse maximale jusqu’au début du lendemain, avant de commencer à s’affaiblir rapidement et de devenir une dépression au début du 26 octobre. Les restes de Xavier ont persisté jusqu’au 28 octobre avant de se dissiper. Aucun décès n’a été signalé à la suite de la tempête, et peu d’impacts ont été signalés dans les îles Salomon et au Vanuatu.

Le 20 octobre 2006, le Service météorologique des Fidji et le Joint Typhoon Warning Center des États-Unis ont commencé à surveiller une dépression tropicale qui s’était formée au sein de la zone de convergence du Pacifique Sud, au nord de la province de Temotu, dans les îles Salomon. Le système se trouvait dans une zone caractérisée par un cisaillement vertical du vent faible à modéré et présentait une bonne évacuation dans ses quadrants nord et est. Au cours de la journée suivante, les conditions entourant le système sont rapidement devenues favorables à une intensification supplémentaire, la convection commençant à s’enrouler autour d’un centre de circulation de bas niveau bien défini. En conséquence, la dépression s’est rapidement développée et a été baptisée Xavier par le FMS le 22 octobre, après être devenue un cyclone tropical de catégorie 1 sur l’échelle australienne d’intensité des cyclones tropicaux. Après que le système a été baptisé, le JTWC a commencé à émettre des bulletins à son sujet et l’a désigné comme cyclone tropical 01P, alors qu’il se trouvait au-dessus des îles Santa Cruz. Tout au long du 22 octobre, l’intensification rapide de Xavier s’est poursuivie : il a développé un œil et est devenu un cyclone tropical sévère de catégorie 3. Ce jour-là, le système a effectué une petite boucle cyclonique au-dessus de la province de Temotu et est passé à proximité de l’île Tikopia des Santa Cruz ou au-dessus de celle-ci. L’intensification rapide du système a ensuite ralenti au cours du 23 octobre, lorsqu’un anticyclone d’altitude situé au nord-ouest du système a entravé son évacuation. Le système a également commencé à se déplacer vers le sud-est ce jour-là, une vallée de basse pression ayant créé une brèche dans la dorsale de hautes pressions qui dirigeait Xavier.


Translated back to English

Severe Tropical Cyclone Xavier was a powerful pre-season cyclone that formed on October 20, 2006, north of the Santa Cruz Islands. Cyclone Xavier was also the most intense storm of the season. Over the following day, it rapidly developed and was classified as Tropical Depression 01F later that day, before being designated Tropical Cyclone Xavier while it was over the Santa Cruz Islands early on October 22. Later on October 22, Xavier intensified into a Category 3 severe tropical cyclone on the Australian tropical cyclone intensity scale, before passing over Tikopia early the following day. Xavier then reached its maximum wind speed of 175 km/h (110 mph over 10 minutes), making it a Category 4 cyclone early on October 24. Xavier maintained its maximum wind speed until early the next day, before beginning to weaken rapidly and becoming a depression early on October 26. Xavier’s remnants persisted until October 28 before dissipating. No deaths were reported as a result of the storm, and few impacts were reported in the Solomon Islands and Vanuatu.

On October 20, 2006, the Fiji Meteorological Service and the United States Joint Typhoon Warning Center began monitoring a tropical depression that had formed within the South Pacific Convergence Zone, north of Temotu Province in the Solomon Islands. The system was located in an area characterized by weak to moderate vertical wind shear and had good outflow in its northern and eastern quadrants. Over the following day, conditions surrounding the system rapidly became favorable for further intensification, with convection beginning to wrap around a well-defined low-level circulation center. As a result, the depression rapidly developed and was named Xavier by the FMS on October 22, after becoming a Category 1 tropical cyclone on the Australian tropical cyclone intensity scale. After the system was named, the JTWC began issuing advisories on it and designated it Tropical Cyclone 01P while it was over the Santa Cruz Islands. Throughout October 22, Xavier’s rapid intensification continued: it developed an eye and became a Category 3 severe tropical cyclone. That day, the system made a small cyclonic loop over Temotu Province and passed near or over Tikopia Island in the Santa Cruz Islands. The system’s rapid intensification then slowed during October 23, when an upper-level anticyclone located northwest of the system hindered its outflow. The system also began moving southeastward that day, as a low-pressure trough created a break in the ridge of high pressure steering Xavier.

Appears to be working as intended. Now need to look at Bert score and edit distance to confirm this across the 20 test samples.

In [27]:
# two possible models to decide between at this stage as discussed in report

models = ["gpt-5.6-terra", "gpt-5.6-luna"]

In [31]:
# now want to loop through 20 texts in test df, and for each carry out light, heavy and back translation (eng > fre > eng)
# and also do this using each of the two possible models

# initialise empty results list
results = []

# loop through test df
for i, (_, row) in enumerate (test.iterrows(), start = 1):

    print(f"\n====== Document {i}/20 ======")
    # get original text and id from test df
    document_id = row["document_id"]
    original_text = row["text"]
    print("Document: ", document_id)

    # now for each of the two possible models, terra and luna
    for model in models:

        print("Model: ", model)

        try:

            # light paraphrase
            # add original text from df into light paraphrase prompt
            light = send_prompt(
                light_para_prompt.format(text = original_text),
                model
            )

            # heavy paraphrase
            # add original text from df into heavy paraphrase prompt
            heavy = send_prompt(
                heavy_para_prompt.format(text = original_text),
                model
            )

            # eng to fre translation
            # add original text from df into translation prompt
            french = send_prompt(
                trans_french_prompt.format(text = original_text),
                model
            )

            # fre to eng translation
            # add french text into translation prompt
            english = send_prompt(
                trans_english_prompt.format(text = french),
                model
            )

            # store output
            results.append({
                "document_id": document_id,
                "source": row["source"],
                "topic": row["topic"],
                "original_text": original_text,
                "model": model,
                "light_paraphrase": light,
                "heavy_paraphrase": heavy,
                "french_translation": french,
                "translation_paraphrase": english
            })

            print(f"Completed: {document_id}, {model}")

        # catch any errors instead of stopping loop
        except Exception as e:

            print("Error:", e)

            # still want to store output to find issue later if necessary
            results.append({
                "document_id": document_id,
                "source": row["source"],
                "topic": row["topic"],
                "original_text": original_text,             
                "model": model,
                "light_paraphrase": None,
                "heavy_paraphrase": None,
                "french_translation": None,
                "translation_paraphrase": None
            })

            print("Failed: ", document_id)

        # small half second pause between models to avoid overuse error
        time.sleep(0.5)

====== Document 1/20 ======
Document:  WIKI_0122
Model:  gpt-5.6-terra
Completed: WIKI_0122, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: WIKI_0122, gpt-5.6-luna

====== Document 2/20 ======
Document:  BBC_0281
Model:  gpt-5.6-terra
Completed: BBC_0281, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: BBC_0281, gpt-5.6-luna

====== Document 3/20 ======
Document:  WIKI_0313
Model:  gpt-5.6-terra
Completed: WIKI_0313, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: WIKI_0313, gpt-5.6-luna

====== Document 4/20 ======
Document:  AMZ_0214
Model:  gpt-5.6-terra
Completed: AMZ_0214, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: AMZ_0214, gpt-5.6-luna

====== Document 5/20 ======
Document:  BBC_0278
Model:  gpt-5.6-terra
Completed: BBC_0278, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: BBC_0278, gpt-5.6-luna

====== Document 6/20 ======
Document:  WIKI_0204
Model:  gpt-5.6-terra
Completed: WIKI_0204, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: WIKI_0204, gpt-5.6-luna

====== Document 7/20 ======
Document:  WIKI_0359
Model:  gpt-5.6-terra
Completed: WIKI_0359, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: WIKI_0359, gpt-5.6-luna

====== Document 8/20 ======
Document:  GUT_0281
Model:  gpt-5.6-terra
Completed: GUT_0281, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: GUT_0281, gpt-5.6-luna

====== Document 9/20 ======
Document:  RED_0322
Model:  gpt-5.6-terra
Completed: RED_0322, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: RED_0322, gpt-5.6-luna

====== Document 10/20 ======
Document:  BBC_0192
Model:  gpt-5.6-terra
Completed: BBC_0192, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: BBC_0192, gpt-5.6-luna

====== Document 11/20 ======
Document:  BBC_0077
Model:  gpt-5.6-terra
Completed: BBC_0077, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: BBC_0077, gpt-5.6-luna

====== Document 12/20 ======
Document:  WIKI_0353
Model:  gpt-5.6-terra
Completed: WIKI_0353, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: WIKI_0353, gpt-5.6-luna

====== Document 13/20 ======
Document:  RED_0142
Model:  gpt-5.6-terra
Completed: RED_0142, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: RED_0142, gpt-5.6-luna

====== Document 14/20 ======
Document:  GUT_0078
Model:  gpt-5.6-terra
Completed: GUT_0078, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: GUT_0078, gpt-5.6-luna

====== Document 15/20 ======
Document:  GUT_0191
Model:  gpt-5.6-terra
Completed: GUT_0191, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: GUT_0191, gpt-5.6-luna

====== Document 16/20 ======
Document:  AMZ_0089
Model:  gpt-5.6-terra
Completed: AMZ_0089, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: AMZ_0089, gpt-5.6-luna

====== Document 17/20 ======
Document:  RED_0084
Model:  gpt-5.6-terra
Completed: RED_0084, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: RED_0084, gpt-5.6-luna

====== Document 18/20 ======
Document:  RED_0228
Model:  gpt-5.6-terra
Completed: RED_0228, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: RED_0228, gpt-5.6-luna

====== Document 19/20 ======
Document:  GUT_0176
Model:  gpt-5.6-terra
Completed: GUT_0176, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: GUT_0176, gpt-5.6-luna

====== Document 20/20 ======
Document:  AMZ_0165
Model:  gpt-5.6-terra
Completed: AMZ_0165, gpt-5.6-terra
Model:  gpt-5.6-luna
Completed: AMZ_0165, gpt-5.6-luna

In [35]:
para_df = pd.DataFrame(results)

In [36]:
para_df

,document_id,source,topic,original_text,model,light_paraphrase,heavy_paraphrase,french_translation,translation_paraphrase
0,WIKI_0122,Wikipedia,History,ʿIzz ad-Dīn ibn Abd al-Qāder ibn Mustafā ibn Y...,gpt-5.6-terra,ʿIzz ad-Dīn ibn Abd al-Qāder ibn Mustafā ibn Y...,ʿIzz ad-Dīn ibn Abd al-Qāder ibn Mustafā ibn Y...,ʿIzz ad-Dīn ibn Abd al-Qāder ibn Mustafā ibn Y...,ʿIzz ad-Dīn ibn Abd al-Qāder ibn Mustafā ibn Y...
1,WIKI_0122,Wikipedia,History,ʿIzz ad-Dīn ibn Abd al-Qāder ibn Mustafā ibn Y...,gpt-5.6-luna,ʿIzz ad-Dīn ibn Abd al-Qāder ibn Mustafā ibn Y...,ʿIzz ad-Dīn ibn Abd al-Qāder ibn Mustafā ibn Y...,ʿIzz ad-Dīn ibn Abd al-Qāder ibn Mustafā ibn Y...,ʿIzz ad-Dīn ibn Abd al-Qāder ibn Mustafā ibn Y...
2,BBC_0281,BBC,General,"Under international law, South Africa had a du...",gpt-5.6-terra,"Under international law, South Africa was obli...",A judge said South Africa was legally obliged ...,"En vertu du droit international, l’Afrique du ...","Under international law, South Africa had a du..."
3,BBC_0281,BBC,General,"Under international law, South Africa had a du...",gpt-5.6-luna,"Under international law, South Africa was obli...",Judge Mohammed Navsa ruled that international ...,"En vertu du droit international, l’Afrique du ...","Under international law, South Africa had a du..."
4,WIKI_0313,Wikipedia,Sports and recreation,"Washington Square, also known as Washington Sq...",gpt-5.6-terra,"Washington Square, also called Washington Squa...","Washington Square, commonly called Washington ...","Washington Square, également connu sous le nom...","Washington Square, also known as Washington Sq..."
5,WIKI_0313,Wikipedia,Sports and recreation,"Washington Square, also known as Washington Sq...",gpt-5.6-luna,"Washington Square, also called Washington Squa...","Washington Square, commonly called Washington ...","Washington Square, également connu sous le nom...","Washington Square, also known as Washington Sq..."
6,AMZ_0214,Amazon reviews,Food reviews,We love Happy Tots food. My 12 month old has t...,gpt-5.6-terra,We love Happy Tots food. My 12-month-old has t...,We are big fans of Happy Tots products. My 12-...,Nous adorons les aliments Happy Tots. Mon enfa...,We love Happy Tots foods. My 12-month-old has ...
7,AMZ_0214,Amazon reviews,Food reviews,We love Happy Tots food. My 12 month old has t...,gpt-5.6-luna,We really like Happy Tots food. My 12-month-ol...,We’re very pleased with Happy Tots food. My 12...,Nous adorons les aliments Happy Tots. Mon bébé...,We love Happy Tots foods. My 12-month-old baby...
8,BBC_0278,BBC,General,Chairman Paulo Sergio Pinheiro urged the inter...,gpt-5.6-terra,Chairman Paulo Sergio Pinheiro called on the i...,"Paulo Sergio Pinheiro, the commission’s chairm...",Le président Paulo Sergio Pinheiro a exhorté l...,Chairman Paulo Sergio Pinheiro urged the inter...
9,BBC_0278,BBC,General,Chairman Paulo Sergio Pinheiro urged the inter...,gpt-5.6-luna,Chairman Paulo Sergio Pinheiro called on the i...,"Paulo Sergio Pinheiro, the commission’s chair,...",Le président Paulo Sergio Pinheiro a exhorté l...,President Paulo Sergio Pinheiro urged the inte...
10,WIKI_0204,Wikipedia,Natural sciences,Severe Tropical Cyclone Xavier was a strong pr...,gpt-5.6-terra,Severe Tropical Cyclone Xavier was a powerful ...,Severe Tropical Cyclone Xavier was an intense ...,Le cyclone tropical intense Xavier était un pu...,Intense Tropical Cyclone Xavier was a powerful...
11,WIKI_0204,Wikipedia,Natural sciences,Severe Tropical Cyclone Xavier was a strong pr...,gpt-5.6-luna,Severe Tropical Cyclone Xavier was a powerful ...,Severe Tropical Cyclone Xavier was a powerful ...,Le cyclone tropical sévère Xavier a été un pui...,Severe Tropical Cyclone Xavier was a powerful ...
12,WIKI_0359,Wikipedia,Social sciences and society,Guillermo Lorenzo Tolentino Eleazar (Tagalog p...,gpt-5.6-terra,Guillermo Lorenzo Tolentino Eleazar (Tagalog p...,Guillermo Lorenzo Tolentino Eleazar (Tagalog p...,Guillermo Lorenzo Tolentino Eleazar (prononcia...,Guillermo Lorenzo Tolentino Eleazar (Tagalog p...
13,WIKI_0359,Wikipedia,Social sciences and society,Guillermo Lorenzo Tolentino Eleazar (Tagalog p...,gpt-5.6-luna,Guillermo Lorenzo Tolentino Eleazar (Tagalog p...,Guillermo Lorenzo Tolentino Eleazar (Tagalog p...,Guillermo Lorenzo Tolentino Eleazar (prononcia...,Guillermo Lorenzo Tolentino Eleazar (Tagalog p...
14,GUT_0281,Gutenberg,Mystery,"Well, after all, dear, perhaps it is well he i...",gpt-5.6-terra,"Well, after all, dear, perhaps it is best that...","“Perhaps, my dear, it is ultimately best that ...","Eh bien, après tout, ma chère, peut-être est-i...","“Well, after all, my dear, perhaps it is bette..."
15,GUT_0281,Gutenberg,Mystery,"Well, after all, dear, perhaps it is well he i...",gpt-5.6-luna,"“Well, after all, dear, perhaps it is for the ...","“Perhaps, my dear, it is better that he has di...","Eh bien, après tout, ma chère, il vaut peut-êt...","“Well, after all, my dear, perhaps it is bette..."
16,RED_0322,Reddit,askscience,I've heard that if you could hypothetically di...,gpt-5.6-terra,I've heard that if you could theoretically dig...,"I have been told that, in the hypothetical cas...",J'ai entendu dire que si l’on pouvait hypothét...,I have heard that if one could hypothetically ...
17,RED_0322,Reddit,askscience,I've heard that if you could hypothetically di...,gpt-5.6-luna,I've heard that if you could hypothetically di...,"I’ve been told that, hypothetically, if you dr...","J’ai entendu dire que, si vous pouviez hypothé...","I’ve heard that, if you could hypothetically d..."
18,BBC_0192,BBC,General,Seven-year-old Rowan Fitzgerald and Dora Hanco...,gpt-5.6-terra,Seven-year-old Rowan Fitzgerald and Dora Hanco...,"Rowan Fitzgerald, aged seven, and Dora Hancox,...","Rowan Fitzgerald, âgé de sept ans, et Dora Han...",Seven-year-old Rowan Fitzgerald and 70-year-ol...
19,BBC_0192,BBC,General,Seven-year-old Rowan Fitzgerald and Dora Hanco...,gpt-5.6-luna,Seven-year-old Rowan Fitzgerald and Dora Hanco...,Seven-year-old Rowan Fitzgerald and Dora Hanco...,"Rowan Fitzgerald, âgé de sept ans, et Dora Han...",Seven-year-old Rowan Fitzgerald and septuagena...
20,BBC_0077,BBC,General,Dr William Stewart said there was bruising and...,gpt-5.6-terra,Dr William Stewart said there was bruising and...,"At the High Court in Glasgow, Dr William Stewa...",Le Dr William Stewart a déclaré qu’il y avait ...,Dr William Stewart said there was bruising and...
21,BBC_0077,BBC,General,Dr William Stewart said there was bruising and...,gpt-5.6-luna,Dr William Stewart said there was bruising and...,Dr William Stewart testified that the right si...,Le Dr William Stewart a déclaré qu’il y avait ...,Dr William Stewart said there were bruising an...
22,WIKI_0353,Wikipedia,Social sciences and society,The National Democratic Party (Spanish: Partid...,gpt-5.6-terra,The National Democratic Party (Spanish: Partid...,The National Democratic Party (Spanish: Partid...,Le Parti national démocratique (espagnol : Par...,The National Democratic Party (Spanish: Partid...
23,WIKI_0353,Wikipedia,Social sciences and society,The National Democratic Party (Spanish: Partid...,gpt-5.6-luna,The National Democratic Party (Spanish: Partid...,The National Democratic Party (Partido Naciona...,Le Parti démocratique national (en espagnol : ...,The National Democratic Party (in Spanish: Par...
24,RED_0142,Reddit,explainlikeimfive,"clevemire did a great job, but just because it...",gpt-5.6-terra,"clevemire did an excellent job, but because th...","Clevemire’s suggestion was excellent, but this...","clevemire a fait un excellent travail, mais co...","clevemire did an excellent job, but since this..."
25,RED_0142,Reddit,explainlikeimfive,"clevemire did a great job, but just because it...",gpt-5.6-luna,"clevemire did an excellent job, but since this...","Clevemire’s suggestion was excellent, but this...","clevemire a fait un excellent travail, mais co...","clevemire did an excellent job, but since this..."
26,GUT_0078,Gutenberg,Fiction,"As soon as they finish one verse, they stop a ...",gpt-5.6-terra,"As soon as they complete one verse, they pause...",No sooner had they completed a verse than they...,"Dès qu’ils ont terminé un couplet, ils s’arrêt...","As soon as they have finished a verse, they st..."
27,GUT_0078,Gutenberg,Fiction,"As soon as they finish one verse, they stop a ...",gpt-5.6-luna,"As soon as they finish one verse, they pause f...","After completing each verse, the children paus...","Dès qu’ils ont fini une strophe, ils s’arrêten...","As soon as they had finished a verse, they sto..."
28,GUT_0191,Gutenberg,English fiction,A very cunning postscript to the telegram brou...,gpt-5.6-terra,A highly cunning postscript to the telegram br...,A shrewd little addition at the end of the tel...,Un post-scriptum très rusé au télégramme amena...,A very crafty postscript to the telegram broug...
29,GUT_0191,Gutenberg,English fiction,A very cunning postscript to the telegram brou...,gpt-5.6-luna,A very cunning postscript to the telegram brou...,A remarkably sly addition to the telegram brou...,Un post-scriptum fort habile ajouté au télégra...,A very clever postscript added to the telegram...
30,AMZ_0089,Amazon reviews,Food reviews,"If you are looking for taste, nutrition, and l...",gpt-5.6-terra,"If you are seeking taste, nutrition, and low c...",For anyone seeking a drink that combines good ...,"Si vous recherchez du goût, de la valeur nutri...","If you are looking for taste, nutritional valu..."
31,AMZ_0089,Amazon reviews,Food reviews,"If you are looking for taste, nutrition, and l...",gpt-5.6-luna,"If you want taste, nutrition, and few carbs/ca...",For anyone seeking a flavorful drink that is n...,"Si vous recherchez le goût, la valeur nutritiv...","If you are looking for flavor, nutritional val..."
32,RED_0084,Reddit,explainlikeimfive,"I grew up Protestant, so I can give a little m...",gpt-5.6-terra,"I was raised Protestant, so I can provide a li...","I was raised Protestant, so I can offer some a...","J’ai grandi dans le protestantisme, donc je pe...","I grew up Protestant, so I can provide a littl..."
33,RED_0084,Reddit,explainlikeimfive,"I grew up Protestant, so I can give a little m...",gpt-5.6-luna,"I was raised Protestant, so I can provide a bi...","I was raised in the Protestant tradition, so I...","J’ai grandi dans le protestantisme, donc je pe...","I grew up in Protestantism, so I can provide a..."
34,RED_0228,Reddit,changemyview,Free migration is more likely good for each of...,gpt-5.6-terra,Free migration is more likely beneficial for e...,Although unrestricted migration is generally b...,La migration libre est plus susceptible d’être...,Free migration is more likely to be beneficial...
35,RED_0228,Reddit,changemyview,Free migration is more likely good for each of...,gpt-5.6-luna,Free migration is more likely to benefit each ...,Free movement across borders is more likely to...,La libre migration a plus de chances d’être bé...,Free migration is more likely to benefit each ...
36,GUT_0176,Gutenberg,English fiction,"I shall not take offense at it."" ""Have you pai...",gpt-5.6-terra,"""I will not take offense at it."" ""Have you pai...","""I will not be offended by it."" ""Have you come...",« Je ne m’en offenserai pas. » « M’avez-vous r...,“I shall not take offence.” “Have you paid me ...
37,GUT_0176,Gutenberg,English fiction,"I shall not take offense at it."" ""Have you pai...",gpt-5.6-luna,“I shall not take offense at it.” “Have you pa...,“I will not be insulted by that.”\n\n“Did you ...,Je ne m’en offenserai pas. » \n« Vous m’avez ...,“I shall not take offense at that.”\n\n“You pa...
38,AMZ_0165,Amazon reviews,Food reviews,This is a nice bag of 1lb of different kinds o...,gpt-5.6-terra,This is a good bag containing 1lb of various t...,"According to the package, this attractive 1-po...",C’est un joli sachet de 1 lb de différentes so...,This is a nice 1 lb bag of different kinds of ...
39,AMZ_0165,Amazon reviews,Food reviews,This is a nice bag of 1lb of different kinds o...,gpt-5.6-luna,This is a nice 1-lb bag containing different t...,This one-pound package contains an assortment ...,C’est un joli sachet d’une livre de différente...,It’s a nice one-pound bag of different kinds o...

In [42]:
print(para_df.iloc[4]["original_text"])
print("\n")
print(para_df.iloc[4]["heavy_paraphrase"])

Washington Square, also known as Washington Square Park, is a public park and registered historic landmark in Chicago, Illinois. Historically known by its nickname Bughouse Square referring to mental health facilities, it was the most celebrated open air free-speech center in the country. It is located across Walton Street from Newberry Library at 901 N. Clark Street in the Near North Side community area of Chicago. Washington Square Park is Chicago's oldest existing small park. It is one of four Chicago Park District parks named after persons surnamed Washington (the others being Washington Park, Harold Washington Park, and Dinah Washington Park). It was added to the National Register of Historic Places on May 20, 1991. On September 4, 1842, the city received a 3-acre (12,000 m2) parcel that was donated by the members of the American Land Company for use as a public park. The property had once been a cow path with a well for farmers to water their cattle. The donors stipulated the name Washington Square. Between 1869 and the 1890s, the city improved Washington Square with lawn, trees, bisecting diagonal walks, limestone coping, picket fencing, and an attractive Victorian fountain. By the time Alderman McCormick became President of Drainage Board in 1906, the fountain had been razed and the park had deteriorated. Alderman McCormick devoted his aldermanic salary to improving the park. He donated a $600 fountain, and the city allocated an additional $10,000 to rehabilitate the park. By the 1910s, the neighborhood surrounding Washington Square had become more diverse. The original purpose of the neighborhood park was as a place of assembly to discuss community issues. Chicago has a long storied history of public speeches both for entertainment and educational purposes. Daniel Burnham's March 27, 1897 lecture for the Commercial Club of Chicago inspired the club to provide $80,000 to publish the Burnham Plan. Washington Square Park has been the geographic center of Chicago public speeches. By the 1890s the park acquired its Bughouse Square moniker. From the 1910s to the mid-1960s, on warm-weather evenings soapbox orators waxed on topics ranging from gender relations to Communism . Like Speakers' Corner in London's Hyde Park, Washington Square became a popular spot for artists, writers, political radicals, and hobos to pontificate, lecture, recite poetry, rant and rave. A group of regulars formed "The Dill Pickle Club," devoted to free expression. For years Washington Square orators appointed their own honorary "king."


Washington Square, commonly called Washington Square Park, is a public green space and designated historic landmark in Chicago, Illinois. Once widely referred to as Bughouse Square—a nickname connected with mental-health institutions—it was regarded as the nation’s foremost outdoor venue for unrestricted speech. The park stands in Chicago’s Near North Side community area, opposite the Newberry Library across Walton Street, at 901 N. Clark Street. It is Chicago’s oldest surviving small park. Washington Square is also one of four Chicago Park District properties bearing the Washington name; the others are Washington Park, Harold Washington Park, and Dinah Washington Park. It was listed on the National Register of Historic Places on May 20, 1991.

On September 4, 1842, members of the American Land Company gave the city a 3-acre (12,000 m2) tract for use as a public park. Before then, the site had served as a cattle trail and contained a well where farmers watered their livestock. The benefactors required that the park be called Washington Square. From 1869 through the 1890s, the city enhanced the grounds by installing grass, trees, diagonal pathways crossing the park, limestone edging, picket fences, and a decorative Victorian-era fountain. However, by 1906, when Alderman McCormick assumed the presidency of the Drainage Board, the fountain had been demolished and the park had fallen into disrepair. McCormick contributed his aldermanic pay toward restoring it, providing a $600 fountain himself, while the city committed another $10,000 for the park’s rehabilitation.

During the 1910s, the area around Washington Square grew increasingly diverse. The neighborhood park had originally been intended as a gathering place where residents could debate local concerns. Chicago has a lengthy and notable tradition of public speaking for both instruction and amusement. Daniel Burnham’s March 27, 1897 address to the Commercial Club of Chicago prompted the organization to spend $80,000 publishing the Burnham Plan. Washington Square Park became the geographic focal point for public speaking in Chicago. By the 1890s, it had gained the Bughouse Square nickname. From the 1910s until the mid-1960s, warm evenings brought soapbox speakers who held forth on subjects from relations between the sexes to Communism. Much like Speakers’ Corner in London’s Hyde Park, Washington Square drew artists, authors, political extremists, and hobos, who delivered speeches, offered lectures, read poetry, and ranted or raved. A core group of frequent participants established the Dill Pickle Club, an organization dedicated to free expression. For many years, the park’s speakers selected their own ceremonial “king.”

Edit distance measures surface-level changes - characters/sequqnces etc. BERT score  measures semantic similarity - the meaning, regardless of the words. 
Edit distance = 0 - 1 @ 0 is identical, 1 different
BERT score = 0 - 1 @ 0 is different, 1 similar meaning
So we expect BERT score to decrease from light to heavy para, and edit to increase. We will wait to see with translation, but expect closer to heavy para stats.

In [3]:
# need to calculate normalized edit distance and BERT scores

# this block calculates edit distance
# loop through the three paraphrase types
for para_type in ["light", "heavy", "translation"]:

    # name of para col.
    paraphrase_col = f"{para_type}_paraphrase"
    # name of score col.
    score_col = f"edit_{para_type}"

    # calculate scores
    para_df[score_col] = para_df.apply(

        # loop row by row to calculate
        lambda row: (

            # calculate edit distance
            distance(
                str(row["original_text"]),
                str(row[paraphrase_col])
            )

            # divide by the longer text (original vs para)
            / max(
                len(str(row["original_text"])),
                len(str(row[paraphrase_col]))
            )
        ),
        axis = 1
    )


# this block calcualtes BERT scores
# get all the original texts
original_texts = para_df["original_text"].tolist()

# loop through the three paraphrase types
for para_type in ["light", "heavy", "translation"]:

    # name of para col.
    paraphrase_col = f"{para_type}_paraphrase"
    # name of score col.
    score_col = f"BERT_{para_type}"

    # get all paraphrases as list
    paraphrases = para_df[paraphrase_col].tolist()

    # get BERT score
    P, R, F1 = score(
        paraphrases,
        original_texts,
        lang = "en",
    )

    # F1 BERT score is the key metric we want, save it for each text
    para_df[score_col] = F1.tolist()

# now create a new DF to inspect the new scores
scores = para_df[
    [
        "document_id",
        "model",
        "BERT_light",
        "BERT_heavy",
        "BERT_translation",
        "edit_light",
        "edit_heavy",
        "edit_translation"
    ]
]

scores.head(20)

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

,document_id,model,BERT_light,BERT_heavy,BERT_translation,edit_light,edit_heavy,edit_translation
0,WIKI_0122,gpt-5.6-terra,0.984579,0.958413,0.981265,0.148148,0.409056,0.139124
1,WIKI_0122,gpt-5.6-luna,0.979677,0.952895,0.972157,0.140893,0.443741,0.190494
2,BBC_0281,gpt-5.6-terra,0.984621,0.943634,0.966811,0.131739,0.389551,0.186259
3,BBC_0281,gpt-5.6-luna,0.966258,0.926601,0.945694,0.147896,0.482012,0.216602
4,WIKI_0313,gpt-5.6-terra,0.971246,0.933661,0.965428,0.197469,0.474788,0.169062
5,WIKI_0313,gpt-5.6-luna,0.976054,0.923002,0.951096,0.137958,0.482304,0.235905
6,AMZ_0214,gpt-5.6-terra,0.981885,0.941472,0.969781,0.078431,0.330402,0.127336
7,AMZ_0214,gpt-5.6-luna,0.983141,0.932601,0.933745,0.119965,0.390390,0.238273
8,BBC_0278,gpt-5.6-terra,0.983235,0.922784,0.957342,0.129776,0.382724,0.222186
9,BBC_0278,gpt-5.6-luna,0.979991,0.919553,0.941283,0.158746,0.497966,0.248489
10,WIKI_0204,gpt-5.6-terra,0.973969,0.943016,0.962336,0.178803,0.480366,0.201677
11,WIKI_0204,gpt-5.6-luna,0.976732,0.932567,0.966237,0.142204,0.527850,0.207396
12,WIKI_0359,gpt-5.6-terra,0.978023,0.946108,0.972977,0.162747,0.428571,0.202390
13,WIKI_0359,gpt-5.6-luna,0.970640,0.946117,0.966329,0.174668,0.418637,0.202899
14,GUT_0281,gpt-5.6-terra,0.970297,0.911602,0.956505,0.158702,0.549698,0.205270
15,GUT_0281,gpt-5.6-luna,0.965663,0.904625,0.942406,0.158579,0.584708,0.208929
16,RED_0322,gpt-5.6-terra,0.971534,0.890367,0.967390,0.182495,0.612254,0.180343
17,RED_0322,gpt-5.6-luna,0.980962,0.896934,0.942794,0.123440,0.597895,0.257409
18,BBC_0192,gpt-5.6-terra,0.981647,0.921465,0.931428,0.105242,0.660097,0.204609
19,BBC_0192,gpt-5.6-luna,0.967259,0.924731,0.934438,0.137790,0.451025,0.238395

NB: As mentioned at top I actually tested paraphrasing in another IPYNB prior to this and this is where I first tested edit / bert scores. Data in report is actually from that IPYNB so the values below might differ slightly.

Looks to be working as intended, lets check means

In [5]:
means = para_df.groupby("model")[
    [
        "BERT_light",
        "BERT_heavy",
        "BERT_translation",
        "edit_light",
        "edit_heavy",
        "edit_translation"
    ]
].mean()

means

,BERT_light,BERT_heavy,BERT_translation,edit_light,edit_heavy,edit_translation
model,,,,,,
gpt-5.6-luna,0.970486,0.914807,0.942565,0.151462,0.513899,0.248215
gpt-5.6-terra,0.978727,0.924639,0.956488,0.138422,0.490558,0.206990

____________

### 2. Create paraphrase dataset

I now move onto paraphrasing the whole 2000 pieces of human written text using the Luna model.

________

In [8]:
# initially only took first 20 rows as a test, now want copy of whole thing

csv_file = "final_human_dataset_copy.csv"
df = pd.read_csv(csv_file)
main = df.copy()

In [9]:
# given the time taken to run the api calls for just the initial 20 texts i forsee this full dataset to take a long time, up to 24 hours.
# dont want it to crash out and if it does, or if my api credit runs out i dont want to have to start from the start again etc. hence
# why this is much more robust than the above code.

In [10]:
# set new output file to contain all original text and info and new paraphrases
output_file = "full_paraphrase_dataset.csv"

# have now decided on luna model
model = "gpt-5.6-luna"


# if this does crash, I want to be able to re-run this cell which should check for existing
# data to determine where to carry on from, rather than re-doing old work
if os.path.exists(output_file):

    # read output file
    para_df = pd.read_csv(output_file)
    # convert df to list of dicts
    results = para_df.to_dict("records")
    # find number completed already
    print("Existing results found: ", len(results))

else:

    # if there were none existing this is first time therefore initialise list
    results = []
    print("Starting from beginning.")



# have established where we are startign from, now need to get the ids of any already complete
completed = {
    row["document_id"]
    for row in results
    if pd.notna(row.get("light_paraphrase"))
    and pd.notna(row.get("heavy_paraphrase"))
    and pd.notna(row.get("translation_paraphrase"))
}
print("Documents completed: ", len(completed))


############################################
# Begin looping through dataset
############################################

# now want to loop through whole dataset, initially skipping any rows that have
# a document ID within completed, established above
for i, (_, row) in enumerate(main.iterrows(), start = 1):

    # get id and text data from csv
    document_id = row["document_id"]
    original_text = row["text"]

    # now look for those ids in completed to see what can be skipped
    if document_id in completed:

        print(
            f"[{i}/{len(main)} ]"
            f"{document_id} already completed"
        )

        # if id existed move onto next and do nothing
        continue

    # otherwise we are now beginning to paraphrase those that havne't been done already
    print(f"\n====== Document {i}/{len(main)} ======")
    print("Document: ", document_id)

    
    ############################################
    # Now we move onto the paraphrasing requests
    ############################################

    try:

        # light paraphrase
        print("Light paraphrase...")
        # add original text from df into light paraphrase prompt
        light = send_prompt(
            light_para_prompt.format(text = original_text),
            model
        )

        # Heavy paraphrase
        print("Heavy paraphrase...")
        # add original text from df into heavy paraphrase prompt
        heavy = send_prompt(
            heavy_para_prompt.format(text = original_text),
            model
        )

        # eng to fre translation
        print("Eng > Fre translation...")
        # add original text from df into translation prompt
        french = send_prompt(
            trans_french_prompt.format(text = original_text),
            model
        )

        # fre to eng translation
        print("Fre > Eng translation...")
        # add french text into translation prompt
        english = send_prompt(
            trans_english_prompt.format(text = french),
            model
        )

        # store output
        results.append({
            "document_id": document_id,
            "source": row["source"],
            "topic": row["topic"],
            "model": model,
            "original_text": original_text,
            "light_paraphrase": light,
            "heavy_paraphrase": heavy,
            "french_translation": french,
            "translation_paraphrase": english
        })

        # also add doc id to completed
        completed.add(document_id)
        print("Document complete")


    ############################################
    # Handle API request errors
    ############################################

    # want to state what the error was and still add the row to the document 
    # so that it is logged and we can continue
    except Exception as e:

        print("Error:", e)

        # still want to store output to find issue later if necessary
        results.append({
            "document_id": document_id,
            "source": row["source"],
            "topic": row["topic"],
            "model": model,
            "original_text": original_text,             
            "light_paraphrase": None,
            "heavy_paraphrase": None,
            "french_translation": None,
            "translation_paraphrase": None
        })

        print("Failed: ", document_id)


    ############################################
    # Save
    ############################################

    # want to save to the csv after each document rather than waiting 
    # until very end in case it crashes
    para_df = pd.DataFrame(results)
    para_df.to_csv(output_file, index = False)
    print("Results saved")
    # small half second pause between models to avoid overuse error
    time.sleep(0.5)

Existing results found:  1907
Documents completed:  1904
[1/2000 ]WIKI_0122 already completed
[2/2000 ]BBC_0281 already completed
[3/2000 ]WIKI_0313 already completed
[4/2000 ]AMZ_0214 already completed
[5/2000 ]BBC_0278 already completed
[6/2000 ]WIKI_0204 already completed
[7/2000 ]WIKI_0359 already completed
[8/2000 ]GUT_0281 already completed
[9/2000 ]RED_0322 already completed
[10/2000 ]BBC_0192 already completed
[11/2000 ]BBC_0077 already completed
[12/2000 ]WIKI_0353 already completed
[13/2000 ]RED_0142 already completed
[14/2000 ]GUT_0078 already completed
[15/2000 ]GUT_0191 already completed
[16/2000 ]AMZ_0089 already completed
[17/2000 ]RED_0084 already completed
[18/2000 ]RED_0228 already completed
[19/2000 ]GUT_0176 already completed
[20/2000 ]AMZ_0165 already completed
[21/2000 ]GUT_0116 already completed
[22/2000 ]BBC_0320 already completed
[23/2000 ]WIKI_0389 already completed
[24/2000 ]WIKI_0012 already completed
[25/2000 ]GUT_0220 already completed
[26/2000 ]GUT_0395 already completed
[27/2000 ]WIKI_0039 already completed
[28/2000 ]GUT_0032 already completed
[29/2000 ]BBC_0272 already completed
[30/2000 ]AMZ_0147 already completed
[31/2000 ]WIKI_0205 already completed
[32/2000 ]AMZ_0021 already completed
[33/2000 ]WIKI_0017 already completed
[34/2000 ]AMZ_0382 already completed
[35/2000 ]GUT_0152 already completed
[36/2000 ]GUT_0309 already completed
[37/2000 ]GUT_0269 already completed
[38/2000 ]GUT_0147 already completed
[39/2000 ]GUT_0238 already completed
[40/2000 ]BBC_0072 already completed
[41/2000 ]WIKI_0338 already completed
[42/2000 ]GUT_0248 already completed
[43/2000 ]BBC_0360 already completed
[44/2000 ]RED_0004 already completed
[45/2000 ]RED_0028 already completed
[46/2000 ]BBC_0358 already completed
[47/2000 ]WIKI_0231 already completed
[48/2000 ]GUT_0345 already completed
[49/2000 ]GUT_0280 already completed
[50/2000 ]BBC_0374 already completed
[51/2000 ]WIKI_0225 already completed
[52/2000 ]WIKI_0283 already completed
[53/2000 ]BBC_0184 already completed
[54/2000 ]WIKI_0399 already completed
[55/2000 ]RED_0079 already completed
[56/2000 ]GUT_0061 already completed
[57/2000 ]RED_0358 already completed
[58/2000 ]AMZ_0194 already completed
[59/2000 ]BBC_0336 already completed
[60/2000 ]RED_0059 already completed
[61/2000 ]WIKI_0147 already completed
[62/2000 ]BBC_0311 already completed
[63/2000 ]GUT_0223 already completed
[64/2000 ]BBC_0365 already completed
[65/2000 ]BBC_0171 already completed
[66/2000 ]BBC_0129 already completed
[67/2000 ]WIKI_0235 already completed
[68/2000 ]WIKI_0107 already completed
[69/2000 ]GUT_0398 already completed
[70/2000 ]BBC_0034 already completed
[71/2000 ]GUT_0168 already completed
[72/2000 ]RED_0346 already completed
[73/2000 ]WIKI_0206 already completed
[74/2000 ]AMZ_0049 already completed
[75/2000 ]WIKI_0288 already completed
[76/2000 ]WIKI_0019 already completed
[77/2000 ]WIKI_0086 already completed
[78/2000 ]BBC_0300 already completed
[79/2000 ]RED_0087 already completed
[80/2000 ]BBC_0341 already completed
[81/2000 ]WIKI_0340 already completed
[82/2000 ]GUT_0034 already completed
[83/2000 ]RED_0005 already completed
[84/2000 ]RED_0345 already completed
[85/2000 ]GUT_0377 already completed
[86/2000 ]WIKI_0312 already completed
[87/2000 ]AMZ_0251 already completed
[88/2000 ]WIKI_0137 already completed
[89/2000 ]WIKI_0174 already completed
[90/2000 ]RED_0052 already completed
[91/2000 ]BBC_0089 already completed
[92/2000 ]AMZ_0397 already completed
[93/2000 ]WIKI_0116 already completed
[94/2000 ]GUT_0340 already completed
[95/2000 ]AMZ_0057 already completed
[96/2000 ]RED_0395 already completed
[97/2000 ]AMZ_0371 already completed
[98/2000 ]BBC_0035 already completed
[99/2000 ]BBC_0078 already completed
[100/2000 ]AMZ_0067 already completed
[101/2000 ]RED_0047 already completed
[102/2000 ]BBC_0225 already completed
[103/2000 ]BBC_0087 already completed
[104/2000 ]BBC_0029 already completed
[105/2000 ]GUT_0051 already completed
[106/2000 ]RED_0125 already completed
[107/2000 ]BBC_0251 already completed
[108/2000 ]RED_0323 already completed
[109/2000 ]RED_0158 already completed
[110/2000 ]BBC_0002 already completed
[111/2000 ]GUT_0218 already completed
[112/2000 ]GUT_0204 already completed
[113/2000 ]AMZ_0051 already completed
[114/2000 ]WIKI_0302 already completed
[115/2000 ]AMZ_0268 already completed
[116/2000 ]WIKI_0125 already completed
[117/2000 ]RED_0006 already completed
[118/2000 ]RED_0294 already completed
[119/2000 ]GUT_0067 already completed
[120/2000 ]AMZ_0362 already completed
[121/2000 ]WIKI_0387 already completed
[122/2000 ]RED_0218 already completed
[123/2000 ]AMZ_0298 already completed
[124/2000 ]BBC_0226 already completed
[125/2000 ]RED_0061 already completed
[126/2000 ]GUT_0035 already completed
[127/2000 ]BBC_0013 already completed
[128/2000 ]RED_0194 already completed
[129/2000 ]WIKI_0073 already completed
[130/2000 ]BBC_0062 already completed
[131/2000 ]BBC_0369 already completed
[132/2000 ]BBC_0377 already completed
[133/2000 ]AMZ_0242 already completed
[134/2000 ]WIKI_0247 already completed
[135/2000 ]RED_0258 already completed
[136/2000 ]GUT_0062 already completed
[137/2000 ]AMZ_0023 already completed
[138/2000 ]WIKI_0084 already completed
[139/2000 ]RED_0211 already completed
[140/2000 ]BBC_0364 already completed
[141/2000 ]AMZ_0046 already completed
[142/2000 ]AMZ_0120 already completed
[143/2000 ]BBC_0378 already completed
[144/2000 ]RED_0063 already completed
[145/2000 ]WIKI_0308 already completed
[146/2000 ]WIKI_0378 already completed
[147/2000 ]RED_0189 already completed
[148/2000 ]WIKI_0180 already completed
[149/2000 ]AMZ_0058 already completed
[150/2000 ]RED_0184 already completed
[151/2000 ]GUT_0386 already completed
[152/2000 ]GUT_0114 already completed
[153/2000 ]BBC_0224 already completed
[154/2000 ]RED_0389 already completed
[155/2000 ]AMZ_0041 already completed
[156/2000 ]WIKI_0277 already completed
[157/2000 ]GUT_0332 already completed
[158/2000 ]RED_0342 already completed
[159/2000 ]RED_0181 already completed
[160/2000 ]RED_0108 already completed
[161/2000 ]AMZ_0151 already completed
[162/2000 ]GUT_0066 already completed
[163/2000 ]BBC_0375 already completed
[164/2000 ]WIKI_0386 already completed
[165/2000 ]RED_0152 already completed
[166/2000 ]GUT_0394 already completed
[167/2000 ]BBC_0004 already completed
[168/2000 ]BBC_0294 already completed
[169/2000 ]RED_0034 already completed
[170/2000 ]GUT_0081 already completed
[171/2000 ]AMZ_0260 already completed
[172/2000 ]BBC_0039 already completed
[173/2000 ]AMZ_0100 already completed
[174/2000 ]BBC_0210 already completed
[175/2000 ]RED_0306 already completed
[176/2000 ]RED_0301 already completed
[177/2000 ]BBC_0359 already completed
[178/2000 ]AMZ_0398 already completed
[179/2000 ]AMZ_0332 already completed
[180/2000 ]RED_0250 already completed
[181/2000 ]WIKI_0184 already completed
[182/2000 ]AMZ_0080 already completed
[183/2000 ]RED_0101 already completed
[184/2000 ]GUT_0027 already completed
[185/2000 ]BBC_0162 already completed
[186/2000 ]RED_0239 already completed
[187/2000 ]WIKI_0118 already completed
[188/2000 ]WIKI_0053 already completed
[189/2000 ]BBC_0174 already completed
[190/2000 ]GUT_0076 already completed
[191/2000 ]GUT_0182 already completed
[192/2000 ]WIKI_0076 already completed
[193/2000 ]WIKI_0278 already completed
[194/2000 ]AMZ_0091 already completed
[195/2000 ]WIKI_0030 already completed
[196/2000 ]GUT_0254 already completed
[197/2000 ]WIKI_0324 already completed
[198/2000 ]RED_0317 already completed
[199/2000 ]WIKI_0254 already completed
[200/2000 ]RED_0021 already completed
[201/2000 ]WIKI_0036 already completed
[202/2000 ]WIKI_0057 already completed
[203/2000 ]GUT_0119 already completed
[204/2000 ]AMZ_0199 already completed
[205/2000 ]GUT_0037 already completed
[206/2000 ]WIKI_0220 already completed
[207/2000 ]AMZ_0002 already completed
[208/2000 ]RED_0314 already completed
[209/2000 ]AMZ_0079 already completed
[210/2000 ]GUT_0362 already completed
[211/2000 ]AMZ_0008 already completed
[212/2000 ]AMZ_0368 already completed
[213/2000 ]WIKI_0227 already completed
[214/2000 ]AMZ_0317 already completed
[215/2000 ]BBC_0263 already completed
[216/2000 ]GUT_0169 already completed
[217/2000 ]BBC_0084 already completed
[218/2000 ]WIKI_0210 already completed
[219/2000 ]GUT_0002 already completed
[220/2000 ]BBC_0353 already completed
[221/2000 ]GUT_0250 already completed
[222/2000 ]AMZ_0153 already completed
[223/2000 ]BBC_0083 already completed
[224/2000 ]GUT_0326 already completed
[225/2000 ]RED_0396 already completed
[226/2000 ]AMZ_0162 already completed
[227/2000 ]AMZ_0305 already completed
[228/2000 ]GUT_0344 already completed
[229/2000 ]GUT_0174 already completed
[230/2000 ]GUT_0230 already completed
[231/2000 ]WIKI_0374 already completed
[232/2000 ]RED_0009 already completed
[233/2000 ]AMZ_0273 already completed
[234/2000 ]RED_0143 already completed
[235/2000 ]RED_0172 already completed
[236/2000 ]GUT_0059 already completed
[237/2000 ]AMZ_0193 already completed
[238/2000 ]WIKI_0062 already completed
[239/2000 ]WIKI_0237 already completed
[240/2000 ]BBC_0065 already completed
[241/2000 ]WIKI_0325 already completed
[242/2000 ]AMZ_0198 already completed
[243/2000 ]BBC_0352 already completed
[244/2000 ]WIKI_0102 already completed
[245/2000 ]BBC_0128 already completed
[246/2000 ]WIKI_0093 already completed
[247/2000 ]WIKI_0287 already completed
[248/2000 ]WIKI_0075 already completed
[249/2000 ]BBC_0299 already completed
[250/2000 ]GUT_0085 already completed
[251/2000 ]GUT_0203 already completed
[252/2000 ]WIKI_0241 already completed
[253/2000 ]GUT_0064 already completed
[254/2000 ]WIKI_0096 already completed
[255/2000 ]RED_0080 already completed
[256/2000 ]RED_0020 already completed
[257/2000 ]AMZ_0154 already completed
[258/2000 ]WIKI_0092 already completed
[259/2000 ]RED_0313 already completed
[260/2000 ]BBC_0189 already completed
[261/2000 ]BBC_0220 already completed
[262/2000 ]AMZ_0178 already completed
[263/2000 ]WIKI_0344 already completed
[264/2000 ]AMZ_0166 already completed
[265/2000 ]WIKI_0343 already completed
[266/2000 ]GUT_0243 already completed
[267/2000 ]AMZ_0146 already completed
[268/2000 ]GUT_0369 already completed
[269/2000 ]RED_0037 already completed
[270/2000 ]GUT_0001 already completed
[271/2000 ]BBC_0227 already completed
[272/2000 ]RED_0018 already completed
[273/2000 ]AMZ_0224 already completed
[274/2000 ]RED_0243 already completed
[275/2000 ]RED_0378 already completed
[276/2000 ]AMZ_0294 already completed
[277/2000 ]RED_0074 already completed
[278/2000 ]RED_0127 already completed
[279/2000 ]GUT_0334 already completed
[280/2000 ]RED_0035 already completed
[281/2000 ]RED_0096 already completed
[282/2000 ]AMZ_0400 already completed
[283/2000 ]AMZ_0390 already completed
[284/2000 ]RED_0150 already completed
[285/2000 ]BBC_0121 already completed
[286/2000 ]RED_0373 already completed
[287/2000 ]RED_0295 already completed
[288/2000 ]GUT_0207 already completed
[289/2000 ]RED_0114 already completed
[290/2000 ]WIKI_0400 already completed
[291/2000 ]AMZ_0204 already completed
[292/2000 ]BBC_0023 already completed
[293/2000 ]WIKI_0165 already completed
[294/2000 ]AMZ_0093 already completed
[295/2000 ]RED_0003 already completed
[296/2000 ]AMZ_0073 already completed
[297/2000 ]BBC_0235 already completed
[298/2000 ]AMZ_0319 already completed
[299/2000 ]WIKI_0011 already completed
[300/2000 ]BBC_0309 already completed
[301/2000 ]AMZ_0391 already completed
[302/2000 ]WIKI_0023 already completed
[303/2000 ]BBC_0067 already completed
[304/2000 ]BBC_0312 already completed
[305/2000 ]AMZ_0019 already completed
[306/2000 ]WIKI_0169 already completed
[307/2000 ]WIKI_0349 already completed
[308/2000 ]RED_0259 already completed
[309/2000 ]WIKI_0272 already completed
[310/2000 ]GUT_0202 already completed
[311/2000 ]BBC_0076 already completed
[312/2000 ]BBC_0398 already completed
[313/2000 ]AMZ_0211 already completed
[314/2000 ]GUT_0258 already completed
[315/2000 ]BBC_0304 already completed
[316/2000 ]BBC_0086 already completed
[317/2000 ]AMZ_0313 already completed
[318/2000 ]GUT_0090 already completed
[319/2000 ]RED_0240 already completed
[320/2000 ]AMZ_0104 already completed
[321/2000 ]GUT_0094 already completed
[322/2000 ]GUT_0322 already completed
[323/2000 ]BBC_0204 already completed
[324/2000 ]WIKI_0158 already completed
[325/2000 ]BBC_0387 already completed
[326/2000 ]GUT_0134 already completed
[327/2000 ]WIKI_0292 already completed
[328/2000 ]BBC_0096 already completed
[329/2000 ]AMZ_0081 already completed
[330/2000 ]RED_0073 already completed
[331/2000 ]RED_0252 already completed
[332/2000 ]BBC_0230 already completed
[333/2000 ]BBC_0093 already completed
[334/2000 ]GUT_0117 already completed
[335/2000 ]RED_0017 already completed
[336/2000 ]GUT_0088 already completed
[337/2000 ]RED_0139 already completed
[338/2000 ]GUT_0255 already completed
[339/2000 ]AMZ_0197 already completed
[340/2000 ]BBC_0381 already completed
[341/2000 ]WIKI_0018 already completed
[342/2000 ]AMZ_0005 already completed
[343/2000 ]AMZ_0333 already completed
[344/2000 ]RED_0013 already completed
[345/2000 ]AMZ_0259 already completed
[346/2000 ]AMZ_0263 already completed
[347/2000 ]AMZ_0072 already completed
[348/2000 ]AMZ_0208 already completed
[349/2000 ]AMZ_0152 already completed
[350/2000 ]GUT_0006 already completed
[351/2000 ]AMZ_0142 already completed
[352/2000 ]BBC_0117 already completed
[353/2000 ]BBC_0012 already completed
[354/2000 ]BBC_0166 already completed
[355/2000 ]BBC_0333 already completed
[356/2000 ]AMZ_0025 already completed
[357/2000 ]BBC_0045 already completed
[358/2000 ]AMZ_0241 already completed
[359/2000 ]AMZ_0059 already completed
[360/2000 ]WIKI_0245 already completed
[361/2000 ]AMZ_0303 already completed
[362/2000 ]BBC_0201 already completed
[363/2000 ]GUT_0025 already completed
[364/2000 ]RED_0180 already completed
[365/2000 ]BBC_0091 already completed
[366/2000 ]AMZ_0140 already completed
[367/2000 ]RED_0081 already completed
[368/2000 ]BBC_0090 already completed
[369/2000 ]AMZ_0357 already completed
[370/2000 ]RED_0359 already completed
[371/2000 ]AMZ_0110 already completed
[372/2000 ]AMZ_0337 already completed
[373/2000 ]RED_0151 already completed
[374/2000 ]RED_0198 already completed
[375/2000 ]BBC_0386 already completed
[376/2000 ]WIKI_0314 already completed
[377/2000 ]AMZ_0348 already completed
[378/2000 ]WIKI_0279 already completed
[379/2000 ]BBC_0169 already completed
[380/2000 ]GUT_0358 already completed
[381/2000 ]AMZ_0234 already completed
[382/2000 ]BBC_0206 already completed
[383/2000 ]RED_0235 already completed
[384/2000 ]RED_0282 already completed
[385/2000 ]GUT_0316 already completed
[386/2000 ]BBC_0191 already completed
[387/2000 ]GUT_0133 already completed
[388/2000 ]AMZ_0148 already completed
[389/2000 ]WIKI_0341 already completed
[390/2000 ]RED_0148 already completed
[391/2000 ]BBC_0330 already completed
[392/2000 ]RED_0118 already completed
[393/2000 ]RED_0299 already completed
[394/2000 ]RED_0331 already completed
[395/2000 ]RED_0255 already completed
[396/2000 ]BBC_0036 already completed
[397/2000 ]WIKI_0003 already completed
[398/2000 ]GUT_0141 already completed
[399/2000 ]RED_0324 already completed
[400/2000 ]GUT_0397 already completed
[401/2000 ]RED_0309 already completed
[402/2000 ]AMZ_0301 already completed
[403/2000 ]WIKI_0337 already completed
[404/2000 ]WIKI_0135 already completed
[405/2000 ]GUT_0277 already completed
[406/2000 ]AMZ_0068 already completed
[407/2000 ]AMZ_0101 already completed
[408/2000 ]GUT_0146 already completed
[409/2000 ]BBC_0172 already completed
[410/2000 ]AMZ_0134 already completed
[411/2000 ]WIKI_0380 already completed
[412/2000 ]GUT_0263 already completed
[413/2000 ]RED_0132 already completed
[414/2000 ]GUT_0237 already completed
[415/2000 ]GUT_0388 already completed
[416/2000 ]GUT_0276 already completed
[417/2000 ]RED_0140 already completed
[418/2000 ]AMZ_0399 already completed
[419/2000 ]RED_0334 already completed
[420/2000 ]GUT_0126 already completed
[421/2000 ]GUT_0159 already completed
[422/2000 ]WIKI_0043 already completed
[423/2000 ]GUT_0184 already completed
[424/2000 ]BBC_0037 already completed
[425/2000 ]WIKI_0200 already completed
[426/2000 ]BBC_0337 already completed
[427/2000 ]GUT_0040 already completed
[428/2000 ]BBC_0197 already completed
[429/2000 ]GUT_0118 already completed
[430/2000 ]AMZ_0218 already completed
[431/2000 ]AMZ_0156 already completed
[432/2000 ]RED_0361 already completed
[433/2000 ]GUT_0185 already completed
[434/2000 ]RED_0195 already completed
[435/2000 ]WIKI_0368 already completed
[436/2000 ]AMZ_0233 already completed
[437/2000 ]GUT_0304 already completed
[438/2000 ]GUT_0142 already completed
[439/2000 ]WIKI_0170 already completed
[440/2000 ]BBC_0318 already completed
[441/2000 ]GUT_0305 already completed
[442/2000 ]AMZ_0167 already completed
[443/2000 ]WIKI_0216 already completed
[444/2000 ]GUT_0132 already completed
[445/2000 ]WIKI_0365 already completed
[446/2000 ]GUT_0273 already completed
[447/2000 ]AMZ_0172 already completed
[448/2000 ]AMZ_0180 already completed
[449/2000 ]AMZ_0040 already completed
[450/2000 ]GUT_0361 already completed
[451/2000 ]GUT_0233 already completed
[452/2000 ]WIKI_0282 already completed
[453/2000 ]GUT_0058 already completed
[454/2000 ]GUT_0172 already completed
[455/2000 ]WIKI_0259 already completed
[456/2000 ]WIKI_0065 already completed
[457/2000 ]AMZ_0276 already completed
[458/2000 ]AMZ_0361 already completed
[459/2000 ]RED_0214 already completed
[460/2000 ]BBC_0289 already completed
[461/2000 ]RED_0285 already completed
[462/2000 ]BBC_0019 already completed
[463/2000 ]BBC_0219 already completed
[464/2000 ]GUT_0162 already completed
[465/2000 ]AMZ_0171 already completed
[466/2000 ]BBC_0146 already completed
[467/2000 ]AMZ_0243 already completed
[468/2000 ]BBC_0150 already completed
[469/2000 ]GUT_0224 already completed
[470/2000 ]RED_0070 already completed
[471/2000 ]RED_0308 already completed
[472/2000 ]BBC_0154 already completed
[473/2000 ]AMZ_0169 already completed
[474/2000 ]BBC_0302 already completed
[475/2000 ]GUT_0112 already completed
[476/2000 ]GUT_0301 already completed
[477/2000 ]WIKI_0056 already completed
[478/2000 ]AMZ_0372 already completed
[479/2000 ]RED_0156 already completed
[480/2000 ]BBC_0268 already completed
[481/2000 ]RED_0222 already completed
[482/2000 ]BBC_0319 already completed
[483/2000 ]RED_0251 already completed
[484/2000 ]GUT_0384 already completed
[485/2000 ]WIKI_0035 already completed
[486/2000 ]GUT_0314 already completed
[487/2000 ]RED_0364 already completed
[488/2000 ]RED_0007 already completed
[489/2000 ]BBC_0368 already completed
[490/2000 ]GUT_0347 already completed
[491/2000 ]AMZ_0275 already completed
[492/2000 ]BBC_0017 already completed
[493/2000 ]WIKI_0328 already completed
[494/2000 ]BBC_0200 already completed
[495/2000 ]WIKI_0038 already completed
[496/2000 ]RED_0319 already completed
[497/2000 ]GUT_0284 already completed
[498/2000 ]AMZ_0195 already completed
[499/2000 ]GUT_0274 already completed
[500/2000 ]WIKI_0258 already completed
[501/2000 ]BBC_0103 already completed
[502/2000 ]WIKI_0213 already completed
[503/2000 ]GUT_0367 already completed
[504/2000 ]GUT_0265 already completed
[505/2000 ]BBC_0400 already completed
[506/2000 ]GUT_0286 already completed
[507/2000 ]WIKI_0369 already completed
[508/2000 ]BBC_0362 already completed
[509/2000 ]BBC_0167 already completed
[510/2000 ]BBC_0240 already completed
[511/2000 ]AMZ_0033 already completed
[512/2000 ]GUT_0313 already completed
[513/2000 ]AMZ_0286 already completed
[514/2000 ]BBC_0389 already completed
[515/2000 ]WIKI_0336 already completed
[516/2000 ]BBC_0385 already completed
[517/2000 ]BBC_0094 already completed
[518/2000 ]BBC_0071 already completed
[519/2000 ]WIKI_0083 already completed
[520/2000 ]GUT_0385 already completed
[521/2000 ]RED_0072 already completed
[522/2000 ]GUT_0060 already completed
[523/2000 ]BBC_0286 already completed
[524/2000 ]GUT_0084 already completed
[525/2000 ]WIKI_0268 already completed

In [11]:
# had to run multiple times so good that it was made so robust, now need to verify that we actually have what we expect and can mvoe on

In [9]:
# re-loading in here

In [10]:
csv_file = "full_paraphrase_dataset.csv"
para_df = pd.read_csv(csv_file)

In [11]:
len(para_df)

2003

In [12]:
len(para_df.columns)

9

2003 is three more than expected so must assume duplicates?

In [13]:
para_df["document_id"].duplicated().sum()

3

In [14]:
duplicates = para_df[para_df["document_id"].duplicated(keep = False)].sort_values("document_id")

In [15]:
duplicates

,document_id,source,topic,model,original_text,light_paraphrase,heavy_paraphrase,french_translation,translation_paraphrase
658,AMZ_0349,Amazon reviews,Food reviews,gpt-5.6-luna,I have an almost insatiable sweet tooth. Left ...,NaN,NaN,NaN,NaN
1908,AMZ_0349,Amazon reviews,Food reviews,gpt-5.6-luna,I have an almost insatiable sweet tooth. Left ...,I have an almost impossible-to-satisfy sweet t...,I have an extremely persistent craving for swe...,J’ai une dent sucrée presque insatiable. Si on...,I have an almost insatiable sweet tooth. If le...
659,GUT_0222,Gutenberg,English fiction,gpt-5.6-luna,"CHAPTER III. “ARCADES AMBO,” BUT FLOURISHING N...",NaN,NaN,NaN,NaN
1909,GUT_0222,Gutenberg,English fiction,gpt-5.6-luna,"CHAPTER III. “ARCADES AMBO,” BUT FLOURISHING N...","CHAPTER III. “ARCADES AMBO,” BUT PROSPERING AL...","CHAPTER III. “ARCADES AMBO,” YET PROSPERING AL...","CHAPITRE III. « ARCADES AMBO », MAIS PROSPÈRE ...","CHAPTER III. “ARCADES AMBO,” BUT PROSPEROUS NE..."
657,RED_0039,Reddit,relationship_advice,gpt-5.6-luna,"Once again, I did not insist that he went. He ...",NaN,NaN,NaN,NaN
1907,RED_0039,Reddit,relationship_advice,gpt-5.6-luna,"Once again, I did not insist that he went. He ...","Once again, I did not demand that he go. He vo...",I never demanded that he come along; he volunt...,"Encore une fois, je n’ai pas insisté pour qu’i...","Once again, I didn’t insist that he come. He o..."

Ahh, these were three that didn't work for some reason on the first pass and were picked up and re-run later but it kept the old ones as NaNs, so need to remove those

In [16]:
para_df = para_df.drop_duplicates(subset = "document_id", keep = "last").reset_index(drop = True)

In [17]:
para_df["document_id"].duplicated().sum()

0

In [18]:
para_df.isna().sum()

document_id               0
source                    0
topic                     0
model                     0
original_text             0
light_paraphrase          0
heavy_paraphrase          0
french_translation        0
translation_paraphrase    0
dtype: int64

Now no duplicates and no NaNs. Should double check word counts to ensure we retained the 350-450 range after paraphrasing.

In [21]:
# split string in each cell in the original text row to words to calculate
# word count, do for every row in column...
para_df["original_word_count"] = (
    para_df["original_text"]
    .fillna("")
    .str.split()
    .str.len()
)

# and do for all 5 text columns...
para_df["light_word_count"] = (
    para_df["light_paraphrase"]
    .fillna("")
    .str.split()
    .str.len()
)

para_df["heavy_word_count"] = (
    para_df["heavy_paraphrase"]
    .fillna("")
    .str.split()
    .str.len()
)

para_df["french_word_count"] = (
    para_df["french_translation"]
    .fillna("")
    .str.split()
    .str.len()
)
para_df["translation_word_count"] = (
    para_df["translation_paraphrase"]
    .fillna("")
    .str.split()
    .str.len()
)

print(para_df[
    [
        "original_word_count",
        "light_word_count",
        "heavy_word_count",
        "french_word_count",
        "translation_word_count"
    ]
].describe())

       original_word_count  light_word_count  heavy_word_count  \
count          2000.000000       2000.000000       2000.000000
mean            398.800000        390.056500        404.742500
std              23.693748         28.240575         35.802054
min             311.000000         17.000000        109.000000
25%             381.000000        374.000000        381.000000
50%             404.000000        395.000000        407.000000
75%             414.000000        408.000000        428.000000
max             451.000000        455.000000        525.000000

       french_word_count  translation_word_count
count        2000.000000             2000.000000
mean          458.612500              408.132000
std            38.413984               28.448044
min           343.000000              265.000000
25%           432.000000              390.000000
50%           458.000000              410.000000
75%           485.000000              426.000000
max           658.000000              605.000000

Some rather large ones I am happy to ignore but there is a 17 word parpahrase which is not acceptable, along with minimums under 300 so need to find and investigate.

In [22]:
# new df containing rows where word count for one of the paraphrases / translations is < 300
short_text = para_df[
    (para_df["light_paraphrase"].fillna("").str.split().str.len() < 300) |
    (para_df["heavy_paraphrase"].fillna("").str.split().str.len() < 300) |
    (para_df["french_translation"].fillna("").str.split().str.len() < 300) |
    (para_df["translation_paraphrase"].fillna("").str.split().str.len() < 300)
    ]

short_text[
    [
        "document_id",
        "original_text",
        "light_paraphrase",
        "heavy_paraphrase",
        "translation_paraphrase"
    ]
]

,document_id,original_text,light_paraphrase,heavy_paraphrase,translation_paraphrase
162,BBC_0375,"The 15-year-old, who is currently staying with...","The 15-year-old, who is currently staying with...",The 15-year-old is currently being sheltered b...,"The 15-year-old girl, who is currently staying..."
277,RED_0127,"For one, the thing about not getting to choose...","For one thing, the idea that you do not get to...","To begin with, the claim that communism means ...","First of all, the idea that you cannot choose ..."
299,BBC_0309,Anatoly Pakhomov said homosexuals were welcome...,Anatoly Pakhomov said homosexuals were welcome...,Sochi mayor Anatoly Pakhomov said gay people w...,Anatoli Pakhomov said that gay people would be...
430,AMZ_0156,Dogswell jerky treat come China. They are not ...,Dogswell jerky treats come from China. They ar...,"Dogswell jerky treats are made in China, and t...",Dogswell dried treats come from China. They ar...
690,RED_0111,"This is my first answer to an ELI5, so stick w...","This is my first answer to an ELI5, so bear wi...",This is my first attempt at answering an ELI5 ...,"This is my first response to an ELI5, so pleas..."
738,BBC_0080,Officer Jason Van Dyke is charged with the fir...,Officer Jason Van Dyke has been charged with t...,Chicago police officer Jason Van Dyke faces a ...,Officer Jason Van Dyke is accused of the first...
975,BBC_0344,Divers from the FBI began searching the waters...,FBI divers began combing the waters of Seccomb...,FBI divers were deployed to Seccombe Lake Park...,FBI divers have begun searching the waters of ...
1437,BBC_0148,Researchers from the Victor Chang Institute in...,Researchers from Sydney’s Victor Chang Institu...,Scientists at Sydney’s Victor Chang Institute ...,Researchers at the Victor Chang Institute in S...
1462,WIKI_0010,South Shore Line Airport Realignment is the na...,South Shore Line Airport Realignment is the na...,The South Shore Line Airport Realignment refer...,The South Shore Line Airport Redevelopment is ...
1511,AMZ_0394,Let me say this first: our family of 6 keeps a...,Let me say this first: our family of 6 follows...,"To begin with, our household of six follows a ...",Let me say this first: our family of six follo...

Can now inspect some of these manually.

In [32]:
para_df[para_df["document_id"] == "BBC_0375"]

,document_id,source,topic,model,original_text,light_paraphrase,heavy_paraphrase,french_translation,translation_paraphrase,original_word_count,light_word_count,heavy_word_count,french_word_count,translation_word_count
162,BBC_0375,BBC,General,gpt-5.6-luna,"The 15-year-old, who is currently staying with...","The 15-year-old, who is currently staying with...",The 15-year-old is currently being sheltered b...,"L’adolescente de 15 ans, qui séjourne actuelle...","The 15-year-old girl, who is currently staying...",357,249,379,432,359

This one is low on the light paraphrase so lets check.

In [23]:
row = para_df[para_df["document_id"] == "BBC_0375"].iloc[0]
print(row["light_paraphrase"])

The 15-year-old, who is currently staying with relatives, has been targeted in an online and in-person harassment campaign. People on Facebook have threatened that “they are going to get” her daughter, the 32-year-old woman told US media. The BBC is not naming the mother to protect the girl’s privacy. About 40 people were reportedly watching the livestream, but no one notified police about the incident. The girl has been too afraid to return to the Lawndale neighbourhood where she lives. Her mother says local children have been ringing her doorbell searching for the girl. “This is simply disturbing, and to think the kids find it funny,” she said, adding that she now wants to leave the crime-ridden west Chicago neighbourhood. “I can’t stay here,” she said on Wednesday after being reunited with her daughter.

Chicago police located the girl one day after she disappeared and contacted Facebook to get the video taken down. The girl has now been released from hospital, but has not yet gone back home. A relative of the girl, Reginald King, says he was the last person to see her before the alleged attack, after they attended church together on Sunday. “Nobody deserves that. No human being deserves for that to happen to them,” he told local media, adding that he believes local “thugs” carried out the attack. Mr King said a local group of children are “holding an entire community hostage”. “I literally saw adults, 60 years old, my elders, my parents’ age, cr

Can see that the text cut out in the middle of the light para for BBC_0375, lets check others.

In [24]:
para_df[para_df["document_id"] == "RED_0127"]

,document_id,source,topic,model,original_text,light_paraphrase,heavy_paraphrase,french_translation,translation_paraphrase,original_word_count,light_word_count,heavy_word_count,french_word_count,translation_word_count
277,RED_0127,Reddit,explainlikeimfive,gpt-5.6-luna,"For one, the thing about not getting to choose...","For one thing, the idea that you do not get to...","To begin with, the claim that communism means ...","Tout d’abord, l’idée selon laquelle on ne peut...","First of all, the idea that you cannot choose ...",407,324,421,416,265

In [25]:
# check the translation 
row = para_df[para_df["document_id"] == "RED_0127"].iloc[0]
print(row["translation_paraphrase"])

First of all, the idea that you cannot choose what you do is simply false. There are many types of communism. Stalinist communism is not the kind that most communists would support, nor is Maoist communism, even though some people believe in them. China used to be communist, but it is now practically as capitalist as any other country, so it is a poor example. The most important idea is that the government owns the means of production. Today, let’s say you go to work in a factory, and you make stuffed animals. You might earn $8 an hour, while the factory owners probably make $16 an hour from your labor. Communists do not like this. They find it absurd that simply owning the factory allows you to profit from everyone else’s work. Instead, they want the government to own the factory. Now, no one makes a profit, but the government provides for all your needs. It will distribute the teddy bears and make sure that everyone has a job to do. Under Stalinism or Maoism, many people could not choose the occupation they pursued, but their leaders were far more focused on industrialization and war than on the interests of the population. If you read Marx, you will see that he was actually very opposed to the idea of forcing people to pursue a single occupation, because he saw it as a form of oppression practically the same as being forced to produce for a factory owner. Here is a quotation from Marx that does not really match the comprehension level of a five-year

Can see it also cut out in the middle of a sentence.

In [26]:
para_df[para_df["document_id"] == "BBC_0309"]

,document_id,source,topic,model,original_text,light_paraphrase,heavy_paraphrase,french_translation,translation_paraphrase,original_word_count,light_word_count,heavy_word_count,french_word_count,translation_word_count
299,BBC_0309,BBC,General,gpt-5.6-luna,Anatoly Pakhomov said homosexuals were welcome...,Anatoly Pakhomov said homosexuals were welcome...,Sochi mayor Anatoly Pakhomov said gay people w...,Anatoli Pakhomov a déclaré que les homosexuels...,Anatoli Pakhomov said that gay people would be...,427,17,439,507,440

In [27]:
row = para_df[para_df["document_id"] == "BBC_0309"].iloc[0]
print(row["light_paraphrase"])

Anatoly Pakhomov said homosexuals were welcome at the Games, provided they “respect Russian law” and “do not

Same again. Its clear that some paraphrases / translations were just cut out midway through for some reason, possibly an issue with the API. Lets check a few more to be sure.

In [28]:
para_df[para_df["document_id"] == "AMZ_0394"]

,document_id,source,topic,model,original_text,light_paraphrase,heavy_paraphrase,french_translation,translation_paraphrase,original_word_count,light_word_count,heavy_word_count,french_word_count,translation_word_count
1511,AMZ_0394,Amazon reviews,Food reviews,gpt-5.6-luna,Let me say this first: our family of 6 keeps a...,Let me say this first: our family of 6 follows...,"To begin with, our household of six follows a ...",Permettez-moi de dire ceci en premier : notre ...,Let me say this first: our family of six follo...,311,289,321,398,320

It appears a word count of 311 for the original slipped through here and so a light paraphrase of 289 is acceptable. No need to delete this one as it still contains appropriate content.

In [30]:
para_df[para_df["document_id"] == "WIKI_0010"]

,document_id,source,topic,model,original_text,light_paraphrase,heavy_paraphrase,french_translation,translation_paraphrase,original_word_count,light_word_count,heavy_word_count,french_word_count,translation_word_count
1462,WIKI_0010,Wikipedia,Engineering and technology,gpt-5.6-luna,South Shore Line Airport Realignment is the na...,South Shore Line Airport Realignment is the na...,The South Shore Line Airport Realignment refer...,Le réaménagement de l’aéroport de la South Sho...,The South Shore Line Airport Redevelopment is ...,401,363,279,435,369

In [31]:
row = para_df[para_df["document_id"] == "WIKI_0010"].iloc[0]
print(row["heavy_paraphrase"])

The South Shore Line Airport Realignment refers to a proposed undertaking that would shift the South Shore Line’s primary terminus in Indiana from its present facility on the eastern side of South Bend International Airport to a newly built station west of the airport. The work would also involve laying new approach tracks. This redesign is expected to shorten travel times because the existing route into the airport station is indirect, slow, and includes numerous at-grade crossings.

The airport’s current station opened on November 20, 1992, and was selected for the east side because a freight spur already existed there. Nevertheless, that location was always regarded as a temporary arrangement for South Bend’s station. In 2006, officials started promoting the idea of transferring the facility to the airport’s western side, and interest in the proposal revived in 2017. Not long afterward, other possible station sites were proposed as well. Several alternatives for replacing the existing terminus have since been examined, although a west-airport station and a Downtown South Bend station became the leading choices. Pete Buttigieg supported the downtown alternative while serving as South Bend’s mayor.

By late 2022, the Northern Indiana Commuter Transportation District (NICTD), which operates the South Shore Line, was moving forward with a plan that could begin construction of a west-side airport station as soon as late 2024, and it commissioned an engineering study in preparation. NICTD has said that constructing the airport facility would not necessarily eliminate the possibility of creating a later connection to Downtown South Bend. Although discussion continued over whether the community should instead pursue a downtown terminus, plans for the west-side airport station were approaching final approval by early 2025.

Again, this is acceptable.

In [32]:
para_df[para_df["document_id"] == "BBC_0148"]

,document_id,source,topic,model,original_text,light_paraphrase,heavy_paraphrase,french_translation,translation_paraphrase,original_word_count,light_word_count,heavy_word_count,french_word_count,translation_word_count
1437,BBC_0148,BBC,General,gpt-5.6-luna,Researchers from the Victor Chang Institute in...,Researchers from Sydney’s Victor Chang Institu...,Scientists at Sydney’s Victor Chang Institute ...,"Des chercheurs de l’Institut Victor Chang, à S...",Researchers at the Victor Chang Institute in S...,377,199,389,464,389

In [33]:
row = para_df[para_df["document_id"] == "BBC_0148"].iloc[0]
print(row["light_paraphrase"])

Researchers from Sydney’s Victor Chang Institute described it as “a double breakthrough”, after identifying both a cause and a preventative solution. With 7.9 million babies born worldwide each year with a birth defect, the team hopes the benefits will be far-reaching. However, one expert said the findings “cannot be translated into recommendations” for pregnancy.

The researchers examined the DNA of four families in which the mothers had experienced repeated miscarriages or their babies had been born with several birth defects, including heart, kidney, vertebrae and cleft palate problems. They identified mutations in two genes that left the child deficient in a vital molecule called Nicotinamide adenine dinucleotide (NAD), which enables cells to produce energy and organs to develop normally.

Lead researcher Prof Sally Dunwoodie reproduced these mutations in mice but discovered they could be corrected if the pregnant mother was given niacin (vitamin B3). “You can increase your NAD levels and completely prevent the miscarriages and birth defects. It bypasses the genetic problem,” she said. “It’s unusual to find a cause and a prevention in the same study. And the prevention is so simple—it’s a vitamin,” she said.

Dr Katie Morris, an expert in maternal foetal medicine at the

This needs replacing. I will go through all now, given that two were acceptable.

In [34]:
para_df[para_df["document_id"] == "BBC_0344"]

,document_id,source,topic,model,original_text,light_paraphrase,heavy_paraphrase,french_translation,translation_paraphrase,original_word_count,light_word_count,heavy_word_count,french_word_count,translation_word_count
975,BBC_0344,BBC,General,gpt-5.6-luna,Divers from the FBI began searching the waters...,FBI divers began combing the waters of Seccomb...,FBI divers were deployed to Seccombe Lake Park...,Des plongeurs du FBI ont commencé à fouiller l...,FBI divers have begun searching the waters of ...,364,271,360,427,371

In [35]:
row = para_df[para_df["document_id"] == "BBC_0344"].iloc[0]
print(row["light_paraphrase"])

FBI divers began combing the waters of Seccombe Lake Park, two miles (3km) from the location of the attack. The two suspects are believed to have visited the park on the day of the shooting, an FBI spokesman said. The attack is being treated as an act of terror, the deadliest in the US since 9/11. Tashfeen Malik and her husband, Syed Farook, opened fire at a workplace gathering for Farook's colleagues, killing 14 people and injuring 22.

Who were the attackers?

San Bernardino shooting: The victims

The couple, who officials say became radicalised several years ago, were both killed in a shoot-out with police hours after the attack. Speaking to reporters at the park on Thursday, the FBI refused to say exactly what the divers were searching for.

"We have indications through leads that at some point they came to this park," said David Bowdich, assistant director in charge of the FBI's Los Angeles field office.

US media, citing law enforcement sources, reported that investigators were looking for electronic devices, including a computer hard drive, connected to the shooters. Earlier on Thursday, FBI Director James Comey and other senior US officials briefed members of Congress on the investigation in a closed-door meeting.

Some US politicians have expressed concern that the couple were not identified by intelligence officials as potential suspects. American officials have said the pair discussed martyrdom and jihad as early as 2013, yet Malik was allowed to enter the US on a fiancée visa last year.

"Everyone's asking the same questions about how it is that law enforcement didn't know, or intelligence officials didn't know, that they could

In [36]:
para_df[para_df["document_id"] == "BBC_0080"]

,document_id,source,topic,model,original_text,light_paraphrase,heavy_paraphrase,french_translation,translation_paraphrase,original_word_count,light_word_count,heavy_word_count,french_word_count,translation_word_count
738,BBC_0080,BBC,General,gpt-5.6-luna,Officer Jason Van Dyke is charged with the fir...,Officer Jason Van Dyke has been charged with t...,Chicago police officer Jason Van Dyke faces a ...,L’agent Jason Van Dyke est accusé du meurtre a...,Officer Jason Van Dyke is accused of the first...,377,88,109,468,383

In [37]:
row = para_df[para_df["document_id"] == "BBC_0080"].iloc[0]
print(row["light_paraphrase"])

Officer Jason Van Dyke has been charged with the first-degree murder of 17-year-old Laquan McDonald, who was stopped by police after slashing car tyres. In a Thanksgiving message on Facebook, the president praised Chicago protesters for maintaining the peace. Four people were arrested overnight as demonstrators marched through the city. The protests were neither as widespread nor as tense as those on Tuesday night, which started moments after police released dashcam footage of the incident. Mr Obama said on Facebook: “Like many Americans, I was deeply disturbed by

In [39]:
para_df[para_df["document_id"] == "RED_0111"]

,document_id,source,topic,model,original_text,light_paraphrase,heavy_paraphrase,french_translation,translation_paraphrase,original_word_count,light_word_count,heavy_word_count,french_word_count,translation_word_count
690,RED_0111,Reddit,explainlikeimfive,gpt-5.6-luna,"This is my first answer to an ELI5, so stick w...","This is my first answer to an ELI5, so bear wi...",This is my first attempt at answering an ELI5 ...,"C’est ma première réponse à un ELI5, alors soy...","This is my first response to an ELI5, so pleas...",352,323,286,371,347

In [41]:
row = para_df[para_df["document_id"] == "RED_0111"].iloc[0]
print(row["heavy_paraphrase"])

This is my first attempt at answering an ELI5 question, so bear with me. Noise-cancelling headphones are a remarkably smart use of a fairly complex electronic system. I do not know enough about the circuitry to explain its technical details, so I will focus on the basic principle.

Each earcup contains a microphone. Together, these microphones listen to the sounds surrounding you, known as ambient noise, and send that information into the headphones’ electronic circuit. The sound is processed as a frequency-based signal, but that part is not essential to understand here. The important point is that sound travels through the air as a wave, much like waves moving across water.

Using the signal from the microphones, the circuit produces something called *antinoise*. This is designed to match the surrounding noise while being its precise opposite. If the ambient sound and the antinoise are played together correctly, they effectively eliminate one another, leaving no audible sound. This happens through a process called *destructive interference*.

To picture destructive interference, think about two water waves. Suppose the peak of one wave lines up perfectly with the dip of another wave, and both are the same size. When those waves overlap, the high part and the low part balance out, leaving the water’s surface flat. In the same way, combining two opposite waves produces a flat signal rather than a larger wave.

With sound, that cancellation is experienced as silence. Therefore, when the headphones detect outside noise and generate an opposing sound wave, the two sounds interfere destructively and cancel each other out. If music is playing at the same time, the unwanted background noise is reduced while the music remains what you hear. I hope that makes sense!

This one is complete so keep.

In [42]:
para_df[para_df["document_id"] == "AMZ_0156"]

,document_id,source,topic,model,original_text,light_paraphrase,heavy_paraphrase,french_translation,translation_paraphrase,original_word_count,light_word_count,heavy_word_count,french_word_count,translation_word_count
430,AMZ_0156,Amazon reviews,Food reviews,gpt-5.6-luna,Dogswell jerky treat come China. They are not ...,Dogswell jerky treats come from China. They ar...,"Dogswell jerky treats are made in China, and t...",Les friandises séchées Dogswell viennent de Ch...,Dogswell dried treats come from China. They ar...,377,192,338,471,383

In [45]:
row = para_df[para_df["document_id"] == "AMZ_0156"].iloc[0]
print(row["light_paraphrase"])

Dogswell jerky treats come from China. They are not safe. I had a Subscribe & Save subscription for the product, but I cancelled it after reading this story from September 15, 2012. (Just search for the article’s title, which is the same as my review.) ---- The FDA now says that 350 dogs and one cat have died over the last 18 months, reportedly after eating chicken jerky treats made in China. An FDA report released this week says they have received 2,200 reports of illnesses connected to the treats—the deaths are included in that number. There is no geographic pattern to the illnesses and deaths—cases have been reported from all 50 states and 6 Canadian provinces. The FDA says most complaints involve chicken jerky (treats, tenders, and strips), but others include duck, sweet potato, and treats in which chicken or duck jerky is wrapped around dried fruits, sweet potatoes, or yams. The report goes on to state that over the past 10 years, there has been a dramatic rise in the importation of pet food from China. It is estimated that nearly 86 million pounds of pet food came from China

Can now remove those that cut our mid-sentence and re-run the program to get them again then check. Note at this point that I did attempt to run through and look for texts that did not end in . ! ? etc. but ereh were hundreds and on inspection most of these were i.e. .) etc. so that wasn't helpful.

In [46]:
# list of ids of records above that cut out midway through paraphrase
incomplete_ids = [
    "BBC_0375",
    "RED_0127",
    "BBC_0309",
    "BBC_0148",
    "BBC_0344",
    "BBC_0080",
    "AMZ_0156"    
]

# delete these rows
para_df = para_df[~para_df["document_id"].isin(incomplete_ids)].reset_index(drop = True)

# dropping 78 from 2000, so expect 1993
print(len(para_df))

1993

We've now trimmed out the NaNs / duplicates, looked for those under 300 words and removed etc. so should now be able to run the main program again. Want to keep all the above text in order for reference so will copy cells down here again for completeness.

In [56]:
# but first need to save my results

para_df.drop(
    columns = [
        "original_word_count",
        "light_word_count",
        "heavy_word_count",
        "french_word_count",
        "translation_word_count",
    ], 
    inplace = True
)
        
para_df.to_csv("full_paraphrase_dataset_2.csv", index = False)

__________

### Re-run to get those last few that didn't complete.

All following cells copied from above.

In [60]:
csv_file = "full_paraphrase_dataset.csv"
df = pd.read_csv(csv_file)
main = df.copy()

In [61]:
# set new output file to contain all original text and info and new paraphrases
output_file = "full_paraphrase_dataset_2.csv"

# have now decided on luna model
model = "gpt-5.6-luna"


# if this does crash, I want to be able to re-run this cell which should check for existing
# data to determine where to carry on from, rather than re-doing old work
if os.path.exists(output_file):

    # read output file
    para_df = pd.read_csv(output_file)
    # convert df to list of dicts
    results = para_df.to_dict("records")
    # find number completed already
    print("Existing results found: ", len(results))

else:

    # if there were none existing this is first time therefore initialise list
    results = []
    print("Starting from beginning.")



# have established where we are startign from, now need to get the ids of any already complete
completed = {
    row["document_id"]
    for row in results
    if pd.notna(row.get("light_paraphrase"))
    and pd.notna(row.get("heavy_paraphrase"))
    and pd.notna(row.get("translation_paraphrase"))
}
print("Documents completed: ", len(completed))


############################################
# Begin looping through dataset
############################################

# now want to loop through whole dataset, initially skipping any rows that have
# a document ID within completed, established above
for i, (_, row) in enumerate(main.iterrows(), start = 1):

    # get id and text data from csv
    document_id = row["document_id"]
    original_text = row["original_text"]

    # now look for those ids in completed to see what can be skipped
    if document_id in completed:

        print(
            f"[{i}/{len(main)} ]"
            f"{document_id} already completed"
        )

        # if id existed move onto next and do nothing
        continue

    # otherwise we are now beginning to paraphrase those that havne't been done already
    print(f"\n====== Document {i}/{len(main)} ======")
    print("Document: ", document_id)

    
    ############################################
    # Now we move onto the paraphrasing requests
    ############################################

    try:

        # light paraphrase
        print("Light paraphrase...")
        # add original text from df into light paraphrase prompt
        light = send_prompt(
            light_para_prompt.format(text = original_text),
            model
        )

        # Heavy paraphrase
        print("Heavy paraphrase...")
        # add original text from df into heavy paraphrase prompt
        heavy = send_prompt(
            heavy_para_prompt.format(text = original_text),
            model
        )

        # eng to fre translation
        print("Eng > Fre translation...")
        # add original text from df into translation prompt
        french = send_prompt(
            trans_french_prompt.format(text = original_text),
            model
        )

        # fre to eng translation
        print("Fre > Eng translation...")
        # add french text into translation prompt
        english = send_prompt(
            trans_english_prompt.format(text = french),
            model
        )

        # store output
        results.append({
            "document_id": document_id,
            "source": row["source"],
            "topic": row["topic"],
            "model": model,
            "original_text": original_text,
            "light_paraphrase": light,
            "heavy_paraphrase": heavy,
            "french_translation": french,
            "translation_paraphrase": english
        })

        # also add doc id to completed
        completed.add(document_id)
        print("Document complete")


    ############################################
    # Handle API request errors
    ############################################

    # want to state what the error was and still add the row to the document 
    # so that it is logged and we can continue
    except Exception as e:

        print("Error:", e)

        # still want to store output to find issue later if necessary
        results.append({
            "document_id": document_id,
            "source": row["source"],
            "topic": row["topic"],
            "model": model,
            "original_text": original_text,             
            "light_paraphrase": None,
            "heavy_paraphrase": None,
            "french_translation": None,
            "translation_paraphrase": None
        })

        print("Failed: ", document_id)


    ############################################
    # Save
    ############################################

    # want to save to the csv after each document rather than waiting 
    # until very end in case it crashes
    para_df = pd.DataFrame(results)
    para_df.to_csv(output_file, index = False)
    print("Results saved")
    # small half second pause between models to avoid overuse error
    time.sleep(0.5)

Existing results found:  1993
Documents completed:  1993
[1/2003 ]WIKI_0122 already completed
[2/2003 ]BBC_0281 already completed
[3/2003 ]WIKI_0313 already completed
[4/2003 ]AMZ_0214 already completed
[5/2003 ]BBC_0278 already completed
[6/2003 ]WIKI_0204 already completed
[7/2003 ]WIKI_0359 already completed
[8/2003 ]GUT_0281 already completed
[9/2003 ]RED_0322 already completed
[10/2003 ]BBC_0192 already completed
[11/2003 ]BBC_0077 already completed
[12/2003 ]WIKI_0353 already completed
[13/2003 ]RED_0142 already completed
[14/2003 ]GUT_0078 already completed
[15/2003 ]GUT_0191 already completed
[16/2003 ]AMZ_0089 already completed
[17/2003 ]RED_0084 already completed
[18/2003 ]RED_0228 already completed
[19/2003 ]GUT_0176 already completed
[20/2003 ]AMZ_0165 already completed
[21/2003 ]GUT_0116 already completed
[22/2003 ]BBC_0320 already completed
[23/2003 ]WIKI_0389 already completed
[24/2003 ]WIKI_0012 already completed
[25/2003 ]GUT_0220 already completed
[26/2003 ]GUT_0395 already completed
[27/2003 ]WIKI_0039 already completed
[28/2003 ]GUT_0032 already completed
[29/2003 ]BBC_0272 already completed
[30/2003 ]AMZ_0147 already completed
[31/2003 ]WIKI_0205 already completed
[32/2003 ]AMZ_0021 already completed
[33/2003 ]WIKI_0017 already completed
[34/2003 ]AMZ_0382 already completed
[35/2003 ]GUT_0152 already completed
[36/2003 ]GUT_0309 already completed
[37/2003 ]GUT_0269 already completed
[38/2003 ]GUT_0147 already completed
[39/2003 ]GUT_0238 already completed
[40/2003 ]BBC_0072 already completed
[41/2003 ]WIKI_0338 already completed
[42/2003 ]GUT_0248 already completed
[43/2003 ]BBC_0360 already completed
[44/2003 ]RED_0004 already completed
[45/2003 ]RED_0028 already completed
[46/2003 ]BBC_0358 already completed
[47/2003 ]WIKI_0231 already completed
[48/2003 ]GUT_0345 already completed
[49/2003 ]GUT_0280 already completed
[50/2003 ]BBC_0374 already completed
[51/2003 ]WIKI_0225 already completed
[52/2003 ]WIKI_0283 already completed
[53/2003 ]BBC_0184 already completed
[54/2003 ]WIKI_0399 already completed
[55/2003 ]RED_0079 already completed
[56/2003 ]GUT_0061 already completed
[57/2003 ]RED_0358 already completed
[58/2003 ]AMZ_0194 already completed
[59/2003 ]BBC_0336 already completed
[60/2003 ]RED_0059 already completed
[61/2003 ]WIKI_0147 already completed
[62/2003 ]BBC_0311 already completed
[63/2003 ]GUT_0223 already completed
[64/2003 ]BBC_0365 already completed
[65/2003 ]BBC_0171 already completed
[66/2003 ]BBC_0129 already completed
[67/2003 ]WIKI_0235 already completed
[68/2003 ]WIKI_0107 already completed
[69/2003 ]GUT_0398 already completed
[70/2003 ]BBC_0034 already completed
[71/2003 ]GUT_0168 already completed
[72/2003 ]RED_0346 already completed
[73/2003 ]WIKI_0206 already completed
[74/2003 ]AMZ_0049 already completed
[75/2003 ]WIKI_0288 already completed
[76/2003 ]WIKI_0019 already completed
[77/2003 ]WIKI_0086 already completed
[78/2003 ]BBC_0300 already completed
[79/2003 ]RED_0087 already completed
[80/2003 ]BBC_0341 already completed
[81/2003 ]WIKI_0340 already completed
[82/2003 ]GUT_0034 already completed
[83/2003 ]RED_0005 already completed
[84/2003 ]RED_0345 already completed
[85/2003 ]GUT_0377 already completed
[86/2003 ]WIKI_0312 already completed
[87/2003 ]AMZ_0251 already completed
[88/2003 ]WIKI_0137 already completed
[89/2003 ]WIKI_0174 already completed
[90/2003 ]RED_0052 already completed
[91/2003 ]BBC_0089 already completed
[92/2003 ]AMZ_0397 already completed
[93/2003 ]WIKI_0116 already completed
[94/2003 ]GUT_0340 already completed
[95/2003 ]AMZ_0057 already completed
[96/2003 ]RED_0395 already completed
[97/2003 ]AMZ_0371 already completed
[98/2003 ]BBC_0035 already completed
[99/2003 ]BBC_0078 already completed
[100/2003 ]AMZ_0067 already completed
[101/2003 ]RED_0047 already completed
[102/2003 ]BBC_0225 already completed
[103/2003 ]BBC_0087 already completed
[104/2003 ]BBC_0029 already completed
[105/2003 ]GUT_0051 already completed
[106/2003 ]RED_0125 already completed
[107/2003 ]BBC_0251 already completed
[108/2003 ]RED_0323 already completed
[109/2003 ]RED_0158 already completed
[110/2003 ]BBC_0002 already completed
[111/2003 ]GUT_0218 already completed
[112/2003 ]GUT_0204 already completed
[113/2003 ]AMZ_0051 already completed
[114/2003 ]WIKI_0302 already completed
[115/2003 ]AMZ_0268 already completed
[116/2003 ]WIKI_0125 already completed
[117/2003 ]RED_0006 already completed
[118/2003 ]RED_0294 already completed
[119/2003 ]GUT_0067 already completed
[120/2003 ]AMZ_0362 already completed
[121/2003 ]WIKI_0387 already completed
[122/2003 ]RED_0218 already completed
[123/2003 ]AMZ_0298 already completed
[124/2003 ]BBC_0226 already completed
[125/2003 ]RED_0061 already completed
[126/2003 ]GUT_0035 already completed
[127/2003 ]BBC_0013 already completed
[128/2003 ]RED_0194 already completed
[129/2003 ]WIKI_0073 already completed
[130/2003 ]BBC_0062 already completed
[131/2003 ]BBC_0369 already completed
[132/2003 ]BBC_0377 already completed
[133/2003 ]AMZ_0242 already completed
[134/2003 ]WIKI_0247 already completed
[135/2003 ]RED_0258 already completed
[136/2003 ]GUT_0062 already completed
[137/2003 ]AMZ_0023 already completed
[138/2003 ]WIKI_0084 already completed
[139/2003 ]RED_0211 already completed
[140/2003 ]BBC_0364 already completed
[141/2003 ]AMZ_0046 already completed
[142/2003 ]AMZ_0120 already completed
[143/2003 ]BBC_0378 already completed
[144/2003 ]RED_0063 already completed
[145/2003 ]WIKI_0308 already completed
[146/2003 ]WIKI_0378 already completed
[147/2003 ]RED_0189 already completed
[148/2003 ]WIKI_0180 already completed
[149/2003 ]AMZ_0058 already completed
[150/2003 ]RED_0184 already completed
[151/2003 ]GUT_0386 already completed
[152/2003 ]GUT_0114 already completed
[153/2003 ]BBC_0224 already completed
[154/2003 ]RED_0389 already completed
[155/2003 ]AMZ_0041 already completed
[156/2003 ]WIKI_0277 already completed
[157/2003 ]GUT_0332 already completed
[158/2003 ]RED_0342 already completed
[159/2003 ]RED_0181 already completed
[160/2003 ]RED_0108 already completed
[161/2003 ]AMZ_0151 already completed
[162/2003 ]GUT_0066 already completed

====== Document 163/2003 ======
Document:  BBC_0375
Light paraphrase...
Heavy paraphrase...
Eng > Fre translation...
Fre > Eng translation...
Document complete
Results saved
[164/2003 ]WIKI_0386 already completed
[165/2003 ]RED_0152 already completed
[166/2003 ]GUT_0394 already completed
[167/2003 ]BBC_0004 already completed
[168/2003 ]BBC_0294 already completed
[169/2003 ]RED_0034 already completed
[170/2003 ]GUT_0081 already completed
[171/2003 ]AMZ_0260 already completed
[172/2003 ]BBC_0039 already completed
[173/2003 ]AMZ_0100 already completed
[174/2003 ]BBC_0210 already completed
[175/2003 ]RED_0306 already completed
[176/2003 ]RED_0301 already completed
[177/2003 ]BBC_0359 already completed
[178/2003 ]AMZ_0398 already completed
[179/2003 ]AMZ_0332 already completed
[180/2003 ]RED_0250 already completed
[181/2003 ]WIKI_0184 already completed
[182/2003 ]AMZ_0080 already completed
[183/2003 ]RED_0101 already completed
[184/2003 ]GUT_0027 already completed
[185/2003 ]BBC_0162 already completed
[186/2003 ]RED_0239 already completed
[187/2003 ]WIKI_0118 already completed
[188/2003 ]WIKI_0053 already completed
[189/2003 ]BBC_0174 already completed
[190/2003 ]GUT_0076 already completed
[191/2003 ]GUT_0182 already completed
[192/2003 ]WIKI_0076 already completed
[193/2003 ]WIKI_0278 already completed
[194/2003 ]AMZ_0091 already completed
[195/2003 ]WIKI_0030 already completed
[196/2003 ]GUT_0254 already completed
[197/2003 ]WIKI_0324 already completed
[198/2003 ]RED_0317 already completed
[199/2003 ]WIKI_0254 already completed
[200/2003 ]RED_0021 already completed
[201/2003 ]WIKI_0036 already completed
[202/2003 ]WIKI_0057 already completed
[203/2003 ]GUT_0119 already completed
[204/2003 ]AMZ_0199 already completed
[205/2003 ]GUT_0037 already completed
[206/2003 ]WIKI_0220 already completed
[207/2003 ]AMZ_0002 already completed
[208/2003 ]RED_0314 already completed
[209/2003 ]AMZ_0079 already completed
[210/2003 ]GUT_0362 already completed
[211/2003 ]AMZ_0008 already completed
[212/2003 ]AMZ_0368 already completed
[213/2003 ]WIKI_0227 already completed
[214/2003 ]AMZ_0317 already completed
[215/2003 ]BBC_0263 already completed
[216/2003 ]GUT_0169 already completed
[217/2003 ]BBC_0084 already completed
[218/2003 ]WIKI_0210 already completed
[219/2003 ]GUT_0002 already completed
[220/2003 ]BBC_0353 already completed
[221/2003 ]GUT_0250 already completed
[222/2003 ]AMZ_0153 already completed
[223/2003 ]BBC_0083 already completed
[224/2003 ]GUT_0326 already completed
[225/2003 ]RED_0396 already completed
[226/2003 ]AMZ_0162 already completed
[227/2003 ]AMZ_0305 already completed
[228/2003 ]GUT_0344 already completed
[229/2003 ]GUT_0174 already completed
[230/2003 ]GUT_0230 already completed
[231/2003 ]WIKI_0374 already completed
[232/2003 ]RED_0009 already completed
[233/2003 ]AMZ_0273 already completed
[234/2003 ]RED_0143 already completed
[235/2003 ]RED_0172 already completed
[236/2003 ]GUT_0059 already completed
[237/2003 ]AMZ_0193 already completed
[238/2003 ]WIKI_0062 already completed
[239/2003 ]WIKI_0237 already completed
[240/2003 ]BBC_0065 already completed
[241/2003 ]WIKI_0325 already completed
[242/2003 ]AMZ_0198 already completed
[243/2003 ]BBC_0352 already completed
[244/2003 ]WIKI_0102 already completed
[245/2003 ]BBC_0128 already completed
[246/2003 ]WIKI_0093 already completed
[247/2003 ]WIKI_0287 already completed
[248/2003 ]WIKI_0075 already completed
[249/2003 ]BBC_0299 already completed
[250/2003 ]GUT_0085 already completed
[251/2003 ]GUT_0203 already completed
[252/2003 ]WIKI_0241 already completed
[253/2003 ]GUT_0064 already completed
[254/2003 ]WIKI_0096 already completed
[255/2003 ]RED_0080 already completed
[256/2003 ]RED_0020 already completed
[257/2003 ]AMZ_0154 already completed
[258/2003 ]WIKI_0092 already completed
[259/2003 ]RED_0313 already completed
[260/2003 ]BBC_0189 already completed
[261/2003 ]BBC_0220 already completed
[262/2003 ]AMZ_0178 already completed
[263/2003 ]WIKI_0344 already completed
[264/2003 ]AMZ_0166 already completed
[265/2003 ]WIKI_0343 already completed
[266/2003 ]GUT_0243 already completed
[267/2003 ]AMZ_0146 already completed
[268/2003 ]GUT_0369 already completed
[269/2003 ]RED_0037 already completed
[270/2003 ]GUT_0001 already completed
[271/2003 ]BBC_0227 already completed
[272/2003 ]RED_0018 already completed
[273/2003 ]AMZ_0224 already completed
[274/2003 ]RED_0243 already completed
[275/2003 ]RED_0378 already completed
[276/2003 ]AMZ_0294 already completed
[277/2003 ]RED_0074 already completed

====== Document 278/2003 ======
Document:  RED_0127
Light paraphrase...
Heavy paraphrase...
Eng > Fre translation...
Fre > Eng translation...
Document complete
Results saved
[279/2003 ]GUT_0334 already completed
[280/2003 ]RED_0035 already completed
[281/2003 ]RED_0096 already completed
[282/2003 ]AMZ_0400 already completed
[283/2003 ]AMZ_0390 already completed
[284/2003 ]RED_0150 already completed
[285/2003 ]BBC_0121 already completed
[286/2003 ]RED_0373 already completed
[287/2003 ]RED_0295 already completed
[288/2003 ]GUT_0207 already completed
[289/2003 ]RED_0114 already completed
[290/2003 ]WIKI_0400 already completed
[291/2003 ]AMZ_0204 already completed
[292/2003 ]BBC_0023 already completed
[293/2003 ]WIKI_0165 already completed
[294/2003 ]AMZ_0093 already completed
[295/2003 ]RED_0003 already completed
[296/2003 ]AMZ_0073 already completed
[297/2003 ]BBC_0235 already completed
[298/2003 ]AMZ_0319 already completed
[299/2003 ]WIKI_0011 already completed

====== Document 300/2003 ======
Document:  BBC_0309
Light paraphrase...
Heavy paraphrase...
Eng > Fre translation...
Fre > Eng translation...
Document complete
Results saved
[301/2003 ]AMZ_0391 already completed
[302/2003 ]WIKI_0023 already completed
[303/2003 ]BBC_0067 already completed
[304/2003 ]BBC_0312 already completed
[305/2003 ]AMZ_0019 already completed
[306/2003 ]WIKI_0169 already completed
[307/2003 ]WIKI_0349 already completed
[308/2003 ]RED_0259 already completed
[309/2003 ]WIKI_0272 already completed
[310/2003 ]GUT_0202 already completed
[311/2003 ]BBC_0076 already completed
[312/2003 ]BBC_0398 already completed
[313/2003 ]AMZ_0211 already completed
[314/2003 ]GUT_0258 already completed
[315/2003 ]BBC_0304 already completed
[316/2003 ]BBC_0086 already completed
[317/2003 ]AMZ_0313 already completed
[318/2003 ]GUT_0090 already completed
[319/2003 ]RED_0240 already completed
[320/2003 ]AMZ_0104 already completed
[321/2003 ]GUT_0094 already completed
[322/2003 ]GUT_0322 already completed
[323/2003 ]BBC_0204 already completed
[324/2003 ]WIKI_0158 already completed
[325/2003 ]BBC_0387 already completed
[326/2003 ]GUT_0134 already completed
[327/2003 ]WIKI_0292 already completed
[328/2003 ]BBC_0096 already completed
[329/2003 ]AMZ_0081 already completed
[330/2003 ]RED_0073 already completed
[331/2003 ]RED_0252 already completed
[332/2003 ]BBC_0230 already completed
[333/2003 ]BBC_0093 already completed
[334/2003 ]GUT_0117 already completed
[335/2003 ]RED_0017 already completed
[336/2003 ]GUT_0088 already completed
[337/2003 ]RED_0139 already completed
[338/2003 ]GUT_0255 already completed
[339/2003 ]AMZ_0197 already completed
[340/2003 ]BBC_0381 already completed
[341/2003 ]WIKI_0018 already completed
[342/2003 ]AMZ_0005 already completed
[343/2003 ]AMZ_0333 already completed
[344/2003 ]RED_0013 already completed
[345/2003 ]AMZ_0259 already completed
[346/2003 ]AMZ_0263 already completed
[347/2003 ]AMZ_0072 already completed
[348/2003 ]AMZ_0208 already completed
[349/2003 ]AMZ_0152 already completed
[350/2003 ]GUT_0006 already completed
[351/2003 ]AMZ_0142 already completed
[352/2003 ]BBC_0117 already completed
[353/2003 ]BBC_0012 already completed
[354/2003 ]BBC_0166 already completed
[355/2003 ]BBC_0333 already completed
[356/2003 ]AMZ_0025 already completed
[357/2003 ]BBC_0045 already completed
[358/2003 ]AMZ_0241 already completed
[359/2003 ]AMZ_0059 already completed
[360/2003 ]WIKI_0245 already completed
[361/2003 ]AMZ_0303 already completed
[362/2003 ]BBC_0201 already completed
[363/2003 ]GUT_0025 already completed
[364/2003 ]RED_0180 already completed
[365/2003 ]BBC_0091 already completed
[366/2003 ]AMZ_0140 already completed
[367/2003 ]RED_0081 already completed
[368/2003 ]BBC_0090 already completed
[369/2003 ]AMZ_0357 already completed
[370/2003 ]RED_0359 already completed
[371/2003 ]AMZ_0110 already completed
[372/2003 ]AMZ_0337 already completed
[373/2003 ]RED_0151 already completed
[374/2003 ]RED_0198 already completed
[375/2003 ]BBC_0386 already completed
[376/2003 ]WIKI_0314 already completed
[377/2003 ]AMZ_0348 already completed
[378/2003 ]WIKI_0279 already completed
[379/2003 ]BBC_0169 already completed
[380/2003 ]GUT_0358 already completed
[381/2003 ]AMZ_0234 already completed
[382/2003 ]BBC_0206 already completed
[383/2003 ]RED_0235 already completed
[384/2003 ]RED_0282 already completed
[385/2003 ]GUT_0316 already completed
[386/2003 ]BBC_0191 already completed
[387/2003 ]GUT_0133 already completed
[388/2003 ]AMZ_0148 already completed
[389/2003 ]WIKI_0341 already completed
[390/2003 ]RED_0148 already completed
[391/2003 ]BBC_0330 already completed
[392/2003 ]RED_0118 already completed
[393/2003 ]RED_0299 already completed
[394/2003 ]RED_0331 already completed
[395/2003 ]RED_0255 already completed
[396/2003 ]BBC_0036 already completed
[397/2003 ]WIKI_0003 already completed
[398/2003 ]GUT_0141 already completed
[399/2003 ]RED_0324 already completed
[400/2003 ]GUT_0397 already completed
[401/2003 ]RED_0309 already completed
[402/2003 ]AMZ_0301 already completed
[403/2003 ]WIKI_0337 already completed
[404/2003 ]WIKI_0135 already completed
[405/2003 ]GUT_0277 already completed
[406/2003 ]AMZ_0068 already completed
[407/2003 ]AMZ_0101 already completed
[408/2003 ]GUT_0146 already completed
[409/2003 ]BBC_0172 already completed
[410/2003 ]AMZ_0134 already completed
[411/2003 ]WIKI_0380 already completed
[412/2003 ]GUT_0263 already completed
[413/2003 ]RED_0132 already completed
[414/2003 ]GUT_0237 already completed
[415/2003 ]GUT_0388 already completed
[416/2003 ]GUT_0276 already completed
[417/2003 ]RED_0140 already completed
[418/2003 ]AMZ_0399 already completed
[419/2003 ]RED_0334 already completed
[420/2003 ]GUT_0126 already completed
[421/2003 ]GUT_0159 already completed
[422/2003 ]WIKI_0043 already completed
[423/2003 ]GUT_0184 already completed
[424/2003 ]BBC_0037 already completed
[425/2003 ]WIKI_0200 already completed
[426/2003 ]BBC_0337 already completed
[427/2003 ]GUT_0040 already completed
[428/2003 ]BBC_0197 already completed
[429/2003 ]GUT_0118 already completed
[430/2003 ]AMZ_0218 already completed

====== Document 431/2003 ======
Document:  AMZ_0156
Light paraphrase...
Heavy paraphrase...
Eng > Fre translation...
Fre > Eng translation...
Document complete
Results saved
[432/2003 ]RED_0361 already completed
[433/2003 ]GUT_0185 already completed
[434/2003 ]RED_0195 already completed
[435/2003 ]WIKI_0368 already completed
[436/2003 ]AMZ_0233 already completed
[437/2003 ]GUT_0304 already completed
[438/2003 ]GUT_0142 already completed
[439/2003 ]WIKI_0170 already completed
[440/2003 ]BBC_0318 already completed
[441/2003 ]GUT_0305 already completed
[442/2003 ]AMZ_0167 already completed
[443/2003 ]WIKI_0216 already completed
[444/2003 ]GUT_0132 already completed
[445/2003 ]WIKI_0365 already completed
[446/2003 ]GUT_0273 already completed
[447/2003 ]AMZ_0172 already completed
[448/2003 ]AMZ_0180 already completed
[449/2003 ]AMZ_0040 already completed
[450/2003 ]GUT_0361 already completed
[451/2003 ]GUT_0233 already completed
[452/2003 ]WIKI_0282 already completed
[453/2003 ]GUT_0058 already completed
[454/2003 ]GUT_0172 already completed
[455/2003 ]WIKI_0259 already completed
[456/2003 ]WIKI_0065 already completed
[457/2003 ]AMZ_0276 already completed
[458/2003 ]AMZ_0361 already completed
[459/2003 ]RED_0214 already completed
[460/2003 ]BBC_0289 already completed
[461/2003 ]RED_0285 already completed
[462/2003 ]BBC_0019 already completed
[463/2003 ]BBC_0219 already completed
[464/2003 ]GUT_0162 already completed
[465/2003 ]AMZ_0171 already completed
[466/2003 ]BBC_0146 already completed
[467/2003 ]AMZ_0243 already completed
[468/2003 ]BBC_0150 already completed
[469/2003 ]GUT_0224 already completed
[470/2003 ]RED_0070 already completed
[471/2003 ]RED_0308 already completed
[472/2003 ]BBC_0154 already completed
[473/2003 ]AMZ_0169 already completed
[474/2003 ]BBC_0302 already completed
[475/2003 ]GUT_0112 already completed
[476/2003 ]GUT_0301 already completed
[477/2003 ]WIKI_0056 already completed
[478/2003 ]AMZ_0372 already completed
[479/2003 ]RED_0156 already completed
[480/2003 ]BBC_0268 already completed
[481/2003 ]RED_0222 already completed
[482/2003 ]BBC_0319 already completed
[483/2003 ]RED_0251 already completed
[484/2003 ]GUT_0384 already completed
[485/2003 ]WIKI_0035 already completed
[486/2003 ]GUT_0314 already completed
[487/2003 ]RED_0364 already completed
[488/2003 ]RED_0007 already completed
[489/2003 ]BBC_0368 already completed
[490/2003 ]GUT_0347 already completed
[491/2003 ]AMZ_0275 already completed
[492/2003 ]BBC_0017 already completed
[493/2003 ]WIKI_0328 already completed
[494/2003 ]BBC_0200 already completed
[495/2003 ]WIKI_0038 already completed
[496/2003 ]RED_0319 already completed
[497/2003 ]GUT_0284 already completed
[498/2003 ]AMZ_0195 already completed
[499/2003 ]GUT_0274 already completed
[500/2003 ]WIKI_0258 already completed
[501/2003 ]BBC_0103 already completed
[502/2003 ]WIKI_0213 already completed
[503/2003 ]GUT_0367 already completed
[504/2003 ]GUT_0265 already completed
[505/2003 ]BBC_0400 already completed
[506/2003 ]GUT_0286 already completed
[507/2003 ]WIKI_0369 already completed
[508/2003 ]BBC_0362 already completed
[509/2003 ]BBC_0167 already completed
[510/2003 ]BBC_0240 already completed

This appears to be complete - can now re-run the same checks from earlier to establish that the dataset is complete.

In [62]:
len(para_df)

2000

In [63]:
para_df["document_id"].duplicated().sum()

0

In [64]:
para_df["document_id"].duplicated().sum()

0

In [66]:
para_df.isna().sum()

document_id               0
source                    0
topic                     0
model                     0
original_text             0
light_paraphrase          0
heavy_paraphrase          0
french_translation        0
translation_paraphrase    0
dtype: int64

In [67]:
# split string in each cell in the original text row to words to calculate
# word count, do for every row in column...
para_df["original_word_count"] = (
    para_df["original_text"]
    .fillna("")
    .str.split()
    .str.len()
)

# and do for all 5 text columns...
para_df["light_word_count"] = (
    para_df["light_paraphrase"]
    .fillna("")
    .str.split()
    .str.len()
)

para_df["heavy_word_count"] = (
    para_df["heavy_paraphrase"]
    .fillna("")
    .str.split()
    .str.len()
)

para_df["french_word_count"] = (
    para_df["french_translation"]
    .fillna("")
    .str.split()
    .str.len()
)
para_df["translation_word_count"] = (
    para_df["translation_paraphrase"]
    .fillna("")
    .str.split()
    .str.len()
)

print(para_df[
    [
        "original_word_count",
        "light_word_count",
        "heavy_word_count",
        "french_word_count",
        "translation_word_count"
    ]
].describe())

       original_word_count  light_word_count  heavy_word_count  \
count          2000.000000       2000.000000       2000.000000
mean            398.800000        390.209500        404.746000
std              23.693748         27.175869         35.780212
min             311.000000        101.000000        112.000000
25%             381.000000        374.000000        381.000000
50%             404.000000        395.000000        407.000000
75%             414.000000        408.000000        428.000000
max             451.000000        455.000000        525.000000

       french_word_count  translation_word_count
count        2000.000000             2000.000000
mean          458.611500              408.177500
std            38.416005               28.303861
min           343.000000              305.000000
25%           432.000000              391.000000
50%           458.000000              410.000000
75%           485.000000              426.000000
max           658.000000              605.000000

It still appears we have some < 300 texts...

RED_0111, WIKI_0010, AMZ_0394 were previously realsied to be small original texts where paraphrasing changed the word count to under 300 and they were therefore acceptable, however the rest appear to have issues. However, on inspection it appears that all these are the light paraphrase only, so i will re-prompt and try one final time.

In [78]:
# prompt copied from above and expanded

light_para_prompt = """

Paraphrase the following text lightly.

YOU MUST PARAPHRASE THE ENTIRE TEXT FROM START TO FINISH.

Make limited changes to the original wording, phrasing and sentence structure.
Replace some words and phrases with alternatives.
Make minor grammatical changes.

Preserve the original meaning, factual information, level of detail, structure and ideas as closely as possible.
The result should be a paraphrase that remains very close to the original text.
Do not add new information, remove information, or summarise the text.

Keep the length similar to the original. The original is 350-450 words so return a paraphrase from 350-450 words.
Continue paraphrasing until you reach the end of the original text.
Do not stop midway through the source.
The paraphrase must end with a complete sentence.

Return only the paraphrased text.


TEXT: {text}

"""

In [79]:
failed_ids = [
    "BBC_0375",	
    "BBC_0309",
    "AMZ_0156",
    "BBC_0080",
    "BBC_0344"
]

In [81]:
for document_id in failed_ids:

    print("Re-prmopting: ", document_id)
    # find row
    row_index = para_df.index[para_df["document_id"] == document_id][0]
    # get original text
    original_text = para_df.loc[row_index, "original_text"]

    # put original text through new light prompt
    new_light_para = send_prompt(
        light_para_prompt.format(
        text = original_text
        ),
        "gpt-5.6-luna"
    )

    # get new word count to be sure
    new_word_count = len(new_light_para.split())
    print("Word count: ", new_word_count)

    # replace the light paraphrase
    para_df.loc[row_index, "light_paraphrase"] = new_light_para
    print("Paraphrase replaced.")

Re-prmopting:  BBC_0375
Word count:  374
Paraphrase replaced.
Re-prmopting:  BBC_0309
Word count:  430
Paraphrase replaced.
Re-prmopting:  AMZ_0156
Word count:  256
Paraphrase replaced.
Re-prmopting:  BBC_0080
Word count:  103
Paraphrase replaced.
Re-prmopting:  BBC_0344
Word count:  282
Paraphrase replaced.

Still happening! Letrs inspect.

In [84]:
para_df[para_df["document_id"] == "AMZ_0156"]["light_paraphrase"].iloc[0]

'Dogswell jerky treats come from China. They are not safe. I had a subscribe-and-save subscription for this product, but I cancelled it after reading this story from September 15, 2012. (Just search for the article’s title, which is also the title of my review.) ---- The FDA now reports that 350 dogs and one cat have died during the past 18 months, reportedly after consuming chicken jerky treats manufactured in China. An FDA report released this week states that the agency has received 2,200 reports of illnesses associated with these treats, with the deaths included in that total. There is no particular geographic pattern connected to the illnesses and deaths; cases have been reported in all 50 states and six Canadian provinces. The FDA says most complaints concern chicken jerky products, including treats, tenders, and strips, although other products involve duck, sweet potato, and treats in which chicken or duck jerky is wrapped around dried fruit, sweet potatoes, or yams.\n\nThe report also explains that over the past 10 years, there has been a significant rise in the importation of pet food from China. It is estimated that almost 86 million pounds of pet food were imported from China in 2011. Pet treats, including jerky treats, are currently regarded as the fastest-growing part of the pet food market. The FDA has been examining the illness reports, but no definite cause has yet been identified. “The ongoing global investigation is complex, multifaceted and includes a wide variety of experts at the FDA including toxicologists, epidemiologists, veterinary researchers,'

In [85]:
para_df[para_df["document_id"] == "BBC_0080"]["light_paraphrase"].iloc[0]

'Officer Jason Van Dyke faces a first-degree murder charge over the shooting of 17-year-old Laquan McDonald, who was stopped by police after reportedly slashing car tyres. In a Thanksgiving post on Facebook, the president praised Chicago protesters for maintaining peace. Four people were arrested overnight while demonstrators marched through the city. The protests were neither as extensive nor as tense as those on Tuesday night, which began shortly after police released dashcam footage of the incident.\n\nMr Obama wrote on Facebook: “Like many Americans, I was deeply disturbed by the footage of the fatal shooting of 17-year-old Laquan McDonald.\n\n“This Thanksgiving, I ask'

In [86]:
para_df[para_df["document_id"] == "BBC_0344"]["light_paraphrase"].iloc[0]

'FBI divers began combing the waters of Seccombe Lake Park, located two miles (3km) from the scene of the attack. An FBI spokesman said the two suspects are believed to have visited the park on the day of the shooting. The incident is being treated as an act of terrorism and is the deadliest attack in the US since 9/11. Tashfeen Malik and her husband, Syed Farook, opened fire during a workplace gathering for Farook’s colleagues, killing 14 people and injuring 22. Who were the attackers? San Bernardino shooting: The victims\n\nOfficials say the couple had become radicalised several years ago. Both were killed in a gun battle with police several hours after the attack. Speaking to reporters at the park on Thursday, the FBI refused to say exactly what the divers were searching for. “We have indications through leads that at some point they came to this park,” said David Bowdich, the FBI assistant director in charge of its Los Angeles field office.\n\nUS media, citing law enforcement sources, reported that investigators are searching for electronic equipment connected to the shooters, including a computer hard drive. Earlier that day, FBI Director James Comey and other senior US officials gave members of Congress a private briefing on the investigation.\n\nSome US politicians have expressed concern that intelligence officials failed to identify the couple as possible suspects. American authorities have said that the pair spoke about martyrdom and jihad as far back as 2013. Despite this, Malik was permitted to enter the United States on a fiancée visa the previous year.\n\n“Everyone’s asking the same questions about how it is that law enforcement didn’t know, or intelligence officials didn’t know, that they could'

\n tabs were cleared out initially in pre-processing so something is going wrong withthe prmpting to re-introduce them. They will be re-cleaned later again so that isn't a worry and I will keep BBC_0344 as it ends with the end of a sentence at almost 300 words but will drop AMZ-0156 and BBC_0080 entirely now.

In [87]:
remove_ids = [
    "AMZ_0156",
    "BBC_0080"
]

para_df = para_df[~para_df["document_id"].isin(remove_ids)].reset_index(drop = True)

In [88]:
len(para_df)

1998

In [90]:
para_df.drop(
    columns = [
        "original_word_count",
        "light_word_count",
        "heavy_word_count",
        "french_word_count",
        "translation_word_count",
    ], 
    inplace = True
)

In [91]:
para_df.to_csv("full_paraphrase_dataset_2.csv", index = False)